package defpackage;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.view.ViewGroup;
import com.google.android.gms.ads.VideoController;
import com.google.android.gms.ads.doubleclick.AppEventListener;
import com.google.android.gms.ads.internal.overlay.zzp;
import com.google.android.gms.ads.internal.util.zzay;
import com.google.android.gms.ads.internal.util.zzf;
import com.google.android.gms.ads.reward.AdMetadataListener;
import com.google.android.gms.internal.ads.zzbar;
import defpackage.n91;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/* loaded from: classes.dex */
public final class qz0 extends ji1 {
    public mb3<sf1<fp2>> A;
    public mb3<aw2<String>> A0;
    public mb3<k61<j41>> A1;
    public mb3<jt1> B;
    public mb3<t82> B0;
    public mb3 B1;
    public mb3<Set<sf1<fp2>>> C;
    public mb3<ad2> C0;
    public mb3<sf1<ud1>> C1;
    public mb3<dy1> D;
    public mb3<ae2> D0;
    public mb3<Set<sf1<ud1>>> D1;
    public mb3<ey1> E;
    public mb3<mb2> E0;
    public mb3<md1> E1;
    public mb3<sf1<fp2>> F;
    public mb3<wc2> F0;
    public mb3<mw1> F1;
    public mb3<Set<sf1<fp2>>> G;
    public mb3<db2> G0;
    public mb3<kv1> G1;
    public mb3 H;
    public mb3<qb2> H0;
    public mb3<au1> H1;
    public mb3<zo2> I;
    public mb3<p92> I0;
    public mb3<zu1> I1;
    public mb3<Context> J;
    public mb3<i52> J0;
    public mb3<sf1<sc1>> J1;
    public mb3<zzf> K;
    public mb3<rc2> K0;
    public mb3<u81> K1;
    public mb3<x11> L;
    public mb3<gd2> L0;
    public mb3<sf1<sc1>> L1;
    public mb3<x22> M;
    public mb3<vh2> M0;
    public mb3<sf1<sc1>> M1;
    public mb3<nz1> N;
    public mb3<ga2> N0;
    public mb3 N1;
    public mb3<v22> O;
    public mb3<String> O0;
    public mb3<sf1<sc1>> O1;
    public mb3<gm2> P;
    public mb3<mc2> P0;
    public mb3<Set<sf1<ua1>>> P1;
    public mb3<sf1<da1>> Q;
    public mb3<na2> Q0;
    public mb3<Set<sf1<ua1>>> Q1;
    public mb3<si2> R;
    public mb3<Set<qd2<? extends nd2<Bundle>>>> R0;
    public mb3<sf1<ca1>> R1;
    public mb3<fr1> S;
    public mb3<pd2<Bundle>> S0;
    public mb3<Set<sf1<ca1>>> S1;
    public mb3<sf1<da1>> T;
    public mb3<g91> T0;
    public mb3<Set<sf1<ca1>>> T1;
    public mb3<cs1> U;
    public mb3<vx1> U0;
    public mb3<sf1<er3>> U1;
    public mb3<ix1> V;
    public mb3<xx1> V0;
    public mb3<sf1<er3>> V1;
    public mb3<sf1<da1>> W;
    public mb3<gy1> W0;
    public mb3<Set<sf1<er3>>> W1;
    public mb3<Set<sf1<da1>>> X;
    public mb3<by1> X0;
    public mb3<Set<sf1<er3>>> X1;
    public mb3<Set<sf1<da1>>> Y;
    public mb3<sf1<da1>> Y0;
    public mb3<sf1<va1>> Y1;
    public mb3<ApplicationInfo> Z;
    public mb3<Set<sf1<da1>>> Z0;
    public mb3<sf1<va1>> Z1;
    public final im2 a;
    public mb3<PackageInfo> a0;
    public mb3<ba1> a1;
    public mb3<Set<sf1<va1>>> a2;
    public final n91 b;
    public mb3<aw2<String>> b0;
    public mb3<gl2> b1;
    public mb3<Set<sf1<va1>>> b2;
    public final hl2 c;
    public mb3<ll2> c0;
    public mb3<hq2> c1;
    public mb3<Set<sf1<hc1>>> c2;
    public final i41 d;
    public mb3<ub2> d0;
    public mb3<gi1> d1;
    public mb3<Set<sf1<xf1>>> d2;
    public final gi1 e;
    public mb3<ViewGroup> e0;
    public mb3<n91.a> e1;
    public mb3<sf1<ob1>> e2;
    public final si2 f;
    public mb3<dk1> f0;
    public mb3<yd1> f1;
    public mb3<sf1<ob1>> f2;
    public final vh2 g;
    public mb3<Set<String>> g0;
    public mb3<o22> g1;
    public mb3<sf1<ob1>> g2;
    public final m71 h;
    public mb3<Set<String>> h0;
    public mb3<Map<String, jz1<l61>>> h1;
    public mb3<Set<sf1<ob1>>> h2;
    public final at1 i;
    public mb3<hb2> i0;
    public mb3<ji1> i1;
    public mb3<Set<sf1<ob1>>> i2;
    public final yd1 j;
    public mb3<nr0> j0;
    public mb3<e22> j1;
    public mb3<Set<sf1<ob1>>> j2;
    public mb3<Context> k;
    public mb3<t71> k0;
    public mb3<g42<kj1, zl2, g12>> k1;
    public mb3<sf1<ob1>> k2;
    public mb3<String> l;
    public mb3<String> l0;
    public mb3<c42> l1;
    public mb3<Set<sf1<AppEventListener>>> l2;
    public mb3<String> m;
    public mb3<t92> m0;
    public mb3<g22> m1;
    public mb3<Set<sf1<AppEventListener>>> m2;
    public mb3<ep3> n;
    public mb3<w82> n0;
    public mb3<g42<kj1, vi0, g12>> n1;
    public mb3<Set<sf1<AppEventListener>>> n2;
    public mb3<yr1> o;
    public mb3<r82> o0;
    public mb3<Map<String, jz1<kj1>>> o1;
    public mb3<ld1> o2;
    public mb3<yr1> p;
    public mb3<zb2> p0;
    public mb3<zzay> p1;
    public mb3<Set<sf1<zzp>>> p2;
    public mb3<Map<ap2, yr1>> q;
    public mb3<e92> q0;
    public mb3<im1> q1;
    public mb3<Set<sf1<VideoController.VideoLifecycleCallbacks>>> q2;
    public mb3<wr1> r;
    public mb3<za2> r0;
    public mb3<b60> r1;
    public mb3<Set<sf1<ra1>>> r2;
    public mb3<Set<sf1<fp2>>> s;
    public mb3 s0;
    public mb3<kc1> s1;
    public mb3<mi2> s2;
    public mb3<xr0> t;
    public mb3<Bundle> t0;
    public mb3<mp1> t1;
    public mb3<Set<sf1<em3>>> t2;
    public mb3<ks1> u;
    public mb3<hc2> u0;
    public mb3<fn1> u1;
    public mb3<Set<sf1<AdMetadataListener>>> u2;
    public mb3 v;
    public mb3<ta2> v0;
    public mb3<sm1> v1;
    public mb3<Set<sf1<AdMetadataListener>>> v2;
    public mb3<rs1> w;
    public mb3<gc2> w0;
    public mb3<cn1> w1;
    public mb3<rb1> w2;
    public mb3 x;
    public mb3<fd2> x0;
    public mb3<om1> x1;
    public final /* synthetic */ pz0 x2;
    public mb3<qp2> y;
    public mb3<o92> y0;
    public mb3<z12> y1;
    public mb3<px1> z;
    public mb3<x92> z0;
    public mb3<Map<String, w12<kj1>>> z1;

    public qz0(pz0 pz0Var, i41 i41Var, gi1 gi1Var, m71 m71Var, em2 em2Var, w81 w81Var, at1 at1Var, yd1 yd1Var, n91 n91Var, im2 im2Var, hl2 hl2Var, si2 si2Var, vh2 vh2Var, oz0 oz0Var) {
        this.x2 = pz0Var;
        this.a = im2Var;
        this.b = n91Var;
        this.c = hl2Var;
        this.d = i41Var;
        this.e = gi1Var;
        this.f = si2Var;
        this.g = vh2Var;
        this.h = m71Var;
        this.i = at1Var;
        this.j = yd1Var;
        km2 km2Var = new km2(im2Var, pz0Var.g);
        this.k = km2Var;
        this.l = new ru1(km2Var);
        mb3 db3Var = wu1.a;
        Object obj = db3.c;
        db3Var = db3Var instanceof db3 ? db3Var : new db3(db3Var);
        this.m = db3Var;
        mb3 mb3VarA = tq1.a(pz0Var.g, this.l, pz0Var.h, ni1.a, db3Var);
        this.n = mb3VarA instanceof db3 ? mb3VarA : new db3(mb3VarA);
        mb3 mb3Var = br1.a;
        this.o = mb3Var instanceof db3 ? mb3Var : new db3(mb3Var);
        mb3 mb3Var2 = dr1.a;
        this.p = mb3Var2 instanceof db3 ? mb3Var2 : new db3(mb3Var2);
        gb3 gb3VarA = eb3.a(2);
        ap2 ap2Var = ap2.SIGNALS;
        mb3<yr1> mb3Var3 = this.o;
        LinkedHashMap<K, mb3<V>> linkedHashMap = gb3VarA.a;
        Objects.requireNonNull(mb3Var3, "provider");
        linkedHashMap.put(ap2Var, mb3Var3);
        ap2 ap2Var2 = ap2.RENDERER;
        mb3<yr1> mb3Var4 = this.p;
        LinkedHashMap<K, mb3<V>> linkedHashMap2 = gb3VarA.a;
        Objects.requireNonNull(mb3Var4, "provider");
        linkedHashMap2.put(ap2Var2, mb3Var4);
        eb3 eb3VarA = gb3VarA.a();
        this.q = eb3VarA;
        xr1 xr1Var = new xr1(this.n, eb3VarA);
        this.r = xr1Var;
        yn2 yn2Var = bo2.a;
        mb3 gr1Var = new gr1(yn2Var, xr1Var);
        this.s = gr1Var instanceof db3 ? gr1Var : new db3(gr1Var);
        nm2 nm2Var = new nm2(im2Var, pz0Var.R);
        this.t = nm2Var;
        mb3 js1Var = new js1(pz0Var.x, nm2Var);
        this.u = js1Var instanceof db3 ? js1Var : new db3(js1Var);
        lb3 lb3VarA = jb3.a(1, 0);
        lb3VarA.a.add(hs1.a);
        jb3 jb3VarA = lb3VarA.a();
        this.v = jb3VarA;
        mb3 ts1Var = new ts1(this.u, jb3VarA, pz0Var.q);
        this.w = ts1Var instanceof db3 ? ts1Var : new db3(ts1Var);
        lb3 lb3VarA2 = jb3.a(1, 0);
        lb3VarA2.a.add(mx1.a);
        this.x = lb3VarA2.a();
        mb3 vu1Var = new vu1(this.m);
        vu1Var = vu1Var instanceof db3 ? vu1Var : new db3(vu1Var);
        this.y = vu1Var;
        mb3 rx1Var = new rx1(this.x, vu1Var);
        rx1Var = rx1Var instanceof db3 ? rx1Var : new db3(rx1Var);
        this.z = rx1Var;
        mb3 fs1Var = new fs1(this.w, yn2Var, rx1Var);
        this.A = fs1Var instanceof db3 ? fs1Var : new db3(fs1Var);
        mb3 nt1Var = new nt1(pz0Var.S, pz0Var.H);
        nt1Var = nt1Var instanceof db3 ? nt1Var : new db3(nt1Var);
        this.B = nt1Var;
        this.C = new kt1(at1Var, nt1Var, yn2Var);
        mb3 db3Var2 = fy1.a;
        db3Var2 = db3Var2 instanceof db3 ? db3Var2 : new db3(db3Var2);
        this.D = db3Var2;
        hy1 hy1Var = new hy1(db3Var2);
        this.E = hy1Var;
        mb3 sx1Var = new sx1(hy1Var, yn2Var);
        this.F = sx1Var instanceof db3 ? sx1Var : new db3(sx1Var);
        lb3 lb3VarA3 = jb3.a(2, 2);
        lb3VarA3.b.add(this.s);
        lb3VarA3.a.add(this.A);
        lb3VarA3.b.add(this.C);
        lb3VarA3.a.add(this.F);
        jb3 jb3VarA2 = lb3VarA3.a();
        this.G = jb3VarA2;
        hp2 hp2Var = new hp2(jb3VarA2);
        this.H = hp2Var;
        mb3 ip2Var = new ip2(yn2Var, pz0Var.m, hp2Var);
        this.I = ip2Var instanceof db3 ? ip2Var : new db3(ip2Var);
        mb3 o91Var = new o91(n91Var, this.k);
        this.J = o91Var instanceof db3 ? o91Var : new db3(o91Var);
        lm2 lm2Var = new lm2(im2Var, pz0Var.R);
        this.K = lm2Var;
        mb3 w11Var = new w11(lm2Var);
        this.L = w11Var instanceof db3 ? w11Var : new db3(w11Var);
        this.M = new a32(pz0Var.a0, pz0Var.r, pz0Var.M, pz0Var.n);
        mb3 db3Var3 = pz1.a;
        db3Var3 = db3Var3 instanceof db3 ? db3Var3 : new db3(db3Var3);
        this.N = db3Var3;
        mb3 we1Var = new we1(yd1Var, pz0Var.q, this.M, db3Var3);
        this.O = we1Var instanceof db3 ? we1Var : new db3(we1Var);
        mb3 jm2Var = new jm2(this.k, this.t);
        jm2Var = jm2Var instanceof db3 ? jm2Var : new db3(jm2Var);
        this.P = jm2Var;
        this.Q = new hm2(em2Var, jm2Var);
        cb3 cb3VarB = fb3.b(si2Var);
        this.R = cb3VarB;
        mb3 mr1Var = new mr1(this.n, cb3VarB);
        mr1Var = mr1Var instanceof db3 ? mr1Var : new db3(mr1Var);
        this.S = mr1Var;
        mb3 vq1Var = new vq1(mr1Var, yn2Var);
        this.T = vq1Var instanceof db3 ? vq1Var : new db3(vq1Var);
        mb3 bs1Var = new bs1(this.u, pz0Var.x);
        this.U = bs1Var instanceof db3 ? bs1Var : new db3(bs1Var);
        mb3 hx1Var = new hx1(this.y, pz0Var.n, this.t);
        hx1Var = hx1Var instanceof db3 ? hx1Var : new db3(hx1Var);
        this.V = hx1Var;
        mb3 ds1Var = new ds1(this.U, yn2Var, hx1Var);
        this.W = ds1Var instanceof db3 ? ds1Var : new db3(ds1Var);
        this.X = new ct1(at1Var, this.B, yn2Var);
        this.Y = new je1(yd1Var);
        mb3<Context> mb3Var5 = this.J;
        lu1 lu1Var = new lu1(mb3Var5);
        this.Z = lu1Var;
        mb3 su1Var = new su1(mb3Var5, lu1Var);
        this.a0 = su1Var instanceof db3 ? su1Var : new db3(su1Var);
        mb3 ju1Var = new ju1(this.I, this.J);
        this.b0 = ju1Var instanceof db3 ? ju1Var : new db3(ju1Var);
        r91 r91Var = new r91(n91Var);
        this.c0 = r91Var;
        this.d0 = new xb2(yn2Var, r91Var, this.a0, this.K);
        this.e0 = new h41(i41Var);
        hi1 hi1Var = new hi1(gi1Var);
        this.f0 = hi1Var;
        this.g0 = new li1(hi1Var);
        lb3 lb3VarA4 = jb3.a(1, 1);
        lb3VarA4.b.add(this.g0);
        mi1 mi1Var = pi1.a;
        lb3VarA4.a.add(mi1Var);
        jb3 jb3VarA3 = lb3VarA4.a();
        this.h0 = jb3VarA3;
        this.i0 = new kb2(pz0Var.T, this.e0, this.J, jb3VarA3);
        mb3 r71Var = new r71(pz0Var.q, this.t, this.c0);
        r71Var = r71Var instanceof db3 ? r71Var : new db3(r71Var);
        this.j0 = r71Var;
        mb3 s71Var = new s71(pz0Var.q, r71Var);
        s71Var = s71Var instanceof db3 ? s71Var : new db3(s71Var);
        this.k0 = s71Var;
        p91 p91Var = new p91(n91Var, s71Var);
        this.l0 = p91Var;
        this.m0 = v92.a(p91Var, pz0Var.w, s71Var, this.P, this.c0);
        mb3<ha2<td2>> mb3Var6 = pz0Var.V;
        mb3<ll2> mb3Var7 = this.c0;
        mb3<Context> mb3Var8 = this.k;
        this.n0 = new y82(mb3Var6, mb3Var7, mb3Var8, pz0Var.R);
        this.o0 = new q82(mb3Var7);
        mb3<zv2> mb3Var9 = pz0Var.T;
        mb3<Set<String>> mb3Var10 = this.h0;
        this.p0 = new bc2(mb3Var9, mb3Var8, mb3Var10);
        this.q0 = new m92(mb3Var9, pz0Var.s, pz0Var.D, pz0Var.W);
        this.r0 = new bb2(this.J, yn2Var);
        this.s0 = new d92(mb3Var10);
        q91 q91Var = new q91(n91Var);
        this.t0 = q91Var;
        this.u0 = new jc2(yn2Var, q91Var);
        mb3<Context> mb3Var11 = this.k;
        this.v0 = new xa2(mb3Var11, yn2Var);
        this.w0 = new fc2(this.Z, this.a0);
        this.x0 = new hd2(this.R);
        this.y0 = new q92(yn2Var, this.c0, pz0Var.h);
        this.z0 = new z92(yn2Var, mb3Var11);
        mb3 ku1Var = new ku1(pz0Var.I, mb3Var11, yn2Var);
        ku1Var = ku1Var instanceof db3 ? ku1Var : new db3(ku1Var);
        this.A0 = ku1Var;
        this.B0 = new u82(ku1Var, yn2Var);
        mb3<Context> mb3Var12 = this.k;
        this.C0 = new cd2(yn2Var, mb3Var12, pz0Var.h);
        this.D0 = new ce2(yn2Var, mb3Var12);
        this.E0 = new ob2(yn2Var);
        this.F0 = new yc2(pz0Var.E, yn2Var, mb3Var12);
        this.G0 = new fb2(yn2Var);
        this.H0 = new sb2(yn2Var, pz0Var.Z);
        this.I0 = new u92(yn2Var, pz0Var.R);
        h52 h52Var = new h52(pz0Var.s);
        mb3<i52> db3Var4 = h52Var instanceof db3 ? h52Var : new db3<>(h52Var);
        this.J0 = db3Var4;
        this.K0 = uc2.a(yn2Var, pz0Var.m, mi1Var, pz0Var.u, this.J, this.c0, db3Var4);
        this.L0 = new od2(yn2Var, this.k);
        cb3 cb3VarB2 = fb3.b(vh2Var);
        this.M0 = cb3VarB2;
        this.N0 = new ja2(cb3VarB2);
        mb3 db3Var5 = pu1.a;
        db3Var5 = db3Var5 instanceof db3 ? db3Var5 : new db3(db3Var5);
        this.O0 = db3Var5;
        this.P0 = new pc2(this.m, db3Var5);
        this.Q0 = new pa2(yn2Var, pz0Var.F, this.c0, mi1Var);
        lb3 lb3VarA5 = jb3.a(30, 0);
        lb3VarA5.a.add(this.d0);
        lb3VarA5.a.add(this.i0);
        lb3VarA5.a.add(this.m0);
        lb3VarA5.a.add(this.n0);
        lb3VarA5.a.add(this.o0);
        lb3VarA5.a.add(this.p0);
        lb3VarA5.a.add(this.q0);
        lb3VarA5.a.add(this.r0);
        lb3VarA5.a.add(this.s0);
        lb3VarA5.a.add(this.u0);
        lb3VarA5.a.add(this.v0);
        lb3VarA5.a.add(this.w0);
        lb3VarA5.a.add(this.x0);
        lb3VarA5.a.add(this.y0);
        lb3VarA5.a.add(this.z0);
        lb3VarA5.a.add(this.B0);
        lb3VarA5.a.add(this.C0);
        lb3VarA5.a.add(pz0Var.V);
        lb3VarA5.a.add(this.D0);
        lb3VarA5.a.add(pz0Var.Y);
        lb3VarA5.a.add(this.E0);
        lb3VarA5.a.add(this.F0);
        lb3VarA5.a.add(this.G0);
        lb3VarA5.a.add(this.H0);
        lb3VarA5.a.add(this.I0);
        lb3VarA5.a.add(this.K0);
        lb3VarA5.a.add(this.L0);
        lb3VarA5.a.add(this.N0);
        lb3VarA5.a.add(this.P0);
        lb3VarA5.a.add(this.Q0);
        jb3 jb3VarA4 = lb3VarA5.a();
        this.R0 = jb3VarA4;
        ud2 ud2Var = new ud2(yn2Var, jb3VarA4);
        this.S0 = ud2Var;
        i91 i91VarA = i91.a(this.I, pz0Var.h, this.Z, this.l, nu1.a, this.a0, this.b0, this.K, this.m, ud2Var);
        this.T0 = i91VarA;
        mb3<Context> mb3Var13 = this.k;
        ux1 ux1Var = new ux1(mb3Var13);
        this.U0 = ux1Var;
        yx1 yx1Var = new yx1(ux1Var, pz0Var.p);
        this.V0 = yx1Var;
        ky1 ky1VarA = ky1.a(mb3Var13, i91VarA, this.D, yx1Var, this.K);
        this.W0 = ky1VarA;
        mb3 ay1Var = new ay1(ky1VarA, this.K);
        ay1Var = ay1Var instanceof db3 ? ay1Var : new db3(ay1Var);
        this.X0 = ay1Var;
        mb3 qx1Var = new qx1(ay1Var, yn2Var);
        this.Y0 = qx1Var instanceof db3 ? qx1Var : new db3(qx1Var);
        lb3 lb3VarA6 = jb3.a(4, 2);
        lb3VarA6.a.add(this.Q);
        lb3VarA6.a.add(this.T);
        lb3VarA6.a.add(this.W);
        lb3VarA6.b.add(this.X);
        lb3VarA6.b.add(this.Y);
        lb3VarA6.a.add(this.Y0);
        jb3 jb3VarA5 = lb3VarA6.a();
        this.Z0 = jb3VarA5;
        mb3 ce1Var = new ce1(yd1Var, jb3VarA5);
        this.a1 = ce1Var instanceof db3 ? ce1Var : new db3(ce1Var);
        s91 s91Var = new s91(n91Var);
        this.b1 = s91Var;
        mb3 mb3VarA2 = gq2.a(this.O, pz0Var.h, this.l0, pz0Var.w, this.J, s91Var, pz0Var.q, pz0Var.I);
        this.c1 = mb3VarA2 instanceof db3 ? mb3VarA2 : new db3(mb3VarA2);
        ii1 ii1Var = new ii1(gi1Var);
        this.d1 = ii1Var;
        u91 u91Var = new u91(n91Var);
        this.e1 = u91Var;
        se1 se1Var = new se1(yd1Var);
        this.f1 = se1Var;
        this.g1 = new n22(pz0Var.H, ii1Var, u91Var, se1Var);
        gb3 gb3VarA2 = eb3.a(1);
        mb3<o22> mb3Var14 = this.g1;
        LinkedHashMap<K, mb3<V>> linkedHashMap3 = gb3VarA2.a;
        Objects.requireNonNull(mb3Var14, "provider");
        linkedHashMap3.put("RecursiveRendererNative", mb3Var14);
        this.h1 = gb3VarA2.a();
        fb3 fb3Var = new fb3(this);
        this.i1 = fb3Var;
        mb3<Context> mb3Var15 = this.J;
        h22 h22Var = new h22(mb3Var15, fb3Var, pz0Var.o);
        this.j1 = h22Var;
        mb3<zo2> mb3Var16 = this.I;
        mb3<zv2> mb3Var17 = pz0Var.T;
        this.k1 = new k42(mb3Var16, mb3Var17, pz0Var.b0, h22Var);
        f42 f42Var = new f42(this.J0);
        this.l1 = f42Var;
        m22 m22Var = new m22(mb3Var15, fb3Var, pz0Var.h);
        this.m1 = m22Var;
        this.n1 = new k42(mb3Var16, mb3Var17, f42Var, m22Var);
        gb3 gb3VarA3 = eb3.a(2);
        mb3<g42<kj1, zl2, g12>> mb3Var18 = this.k1;
        LinkedHashMap<K, mb3<V>> linkedHashMap4 = gb3VarA3.a;
        Objects.requireNonNull(mb3Var18, "provider");
        linkedHashMap4.put("ThirdPartyRenderer", mb3Var18);
        mb3<g42<kj1, vi0, g12>> mb3Var19 = this.n1;
        LinkedHashMap<K, mb3<V>> linkedHashMap5 = gb3VarA3.a;
        Objects.requireNonNull(mb3Var19, "provider");
        linkedHashMap5.put("RtbRendererNative", mb3Var19);
        this.o1 = gb3VarA3.a();
        mb3<zzay> mb3VarA3 = kb3.a(new g11(pz0Var.g));
        this.p1 = mb3VarA3;
        this.q1 = kb3.a(new km1(mb3VarA3, pz0Var.q, yn2Var));
        mb3 db3Var6 = d60.a;
        db3Var6 = db3Var6 instanceof db3 ? db3Var6 : new db3(db3Var6);
        this.r1 = db3Var6;
        f91 f91Var = new f91(pz0Var.j0);
        this.s1 = f91Var;
        mb3 mb3VarA4 = aq1.a(h11.a, this.J, pz0Var.I, db3Var6, pz0Var.h, pz0Var.J, this.n, f91Var);
        mb3VarA4 = mb3VarA4 instanceof db3 ? mb3VarA4 : new db3(mb3VarA4);
        this.t1 = mb3VarA4;
        vn1 vn1Var = new vn1(this.c0, pz0Var.o, mb3VarA4);
        mb3<fn1> db3Var7 = vn1Var instanceof db3 ? vn1Var : new db3<>(vn1Var);
        this.u1 = db3Var7;
        zm1 zm1Var = new zm1(this.J, this.q1, pz0Var.I, pz0Var.h, pz0Var.J, this.n, yn2Var, this.c0, db3Var7, pz0Var.m);
        this.v1 = zm1Var;
        gn1 gn1Var = new gn1(yn2Var, zm1Var);
        this.w1 = gn1Var;
        pm1 pm1Var = new pm1(yn2Var, zm1Var, gn1Var);
        this.x1 = pm1Var;
        this.y1 = new f22(this.i1, yn2Var, pm1Var, pz0Var.O);
        gb3 gb3VarA4 = eb3.a(1);
        mb3<z12> mb3Var20 = this.y1;
        LinkedHashMap<K, mb3<V>> linkedHashMap6 = gb3VarA4.a;
        Objects.requireNonNull(mb3Var20, "provider");
        linkedHashMap6.put("FirstPartyRenderer", mb3Var20);
        this.z1 = gb3VarA4.a();
        oi1 oi1Var = new oi1(pz0Var.H, this.e1, this.f1, this.d1, pz0Var.j0);
        mb3<k61<j41>> db3Var8 = oi1Var instanceof db3 ? oi1Var : new db3<>(oi1Var);
        this.A1 = db3Var8;
        mb3 di1Var = new di1(this.h1, this.o1, this.z1, db3Var8, this.f0);
        this.B1 = di1Var instanceof db3 ? di1Var : new db3(di1Var);
        mb3 xq1Var = new xq1(this.S, yn2Var);
        this.C1 = xq1Var instanceof db3 ? xq1Var : new db3(xq1Var);
        lb3 lb3VarA7 = jb3.a(1, 0);
        lb3VarA7.a.add(this.C1);
        jb3 jb3VarA6 = lb3VarA7.a();
        this.D1 = jb3VarA6;
        mb3 vd1Var = new vd1(jb3VarA6);
        this.E1 = vd1Var instanceof db3 ? vd1Var : new db3(vd1Var);
        cx1 cx1VarA = cx1.a(pz0Var.g, pz0Var.o, nz0.a, pz0Var.c0, pz0Var.d0, pz0Var.e0);
        this.F1 = cx1VarA;
        uu1 uu1Var = new uu1(this.J);
        this.G1 = uu1Var;
        eu1 eu1Var = new eu1(fo2.a, yn2Var, uu1Var, cx1VarA);
        this.H1 = eu1Var;
        this.I1 = dv1.a(this.c0, eu1Var, yn2Var, pz0Var.m, this.D);
        mb3 zq1Var = new zq1(this.S, yn2Var);
        this.J1 = zq1Var instanceof db3 ? zq1Var : new db3(zq1Var);
        mb3 mb3VarA5 = t81.a(this.k, this.c0, pz0Var.h, this.K, pz0Var.D);
        mb3VarA5 = mb3VarA5 instanceof db3 ? mb3VarA5 : new db3(mb3VarA5);
        this.K1 = mb3VarA5;
        mb3 v81Var = new v81(w81Var, mb3VarA5);
        this.L1 = v81Var instanceof db3 ? v81Var : new db3(v81Var);
        mb3 es1Var = new es1(this.U, yn2Var, this.V);
        this.M1 = es1Var instanceof db3 ? es1Var : new db3(es1Var);
        vv1 vv1Var = new vv1(this.k, pz0Var.E);
        this.N1 = vv1Var;
        mb3 mu1Var = new mu1(vv1Var, yn2Var);
        this.O1 = mu1Var instanceof db3 ? mu1Var : new db3(mu1Var);
        mb3<jt1> mb3Var21 = this.B;
        this.P1 = new ft1(at1Var, mb3Var21, yn2Var);
        this.Q1 = new be1(yd1Var);
        mb3<t71> mb3Var22 = this.k0;
        this.R1 = new n71(m71Var, mb3Var22);
        this.S1 = new dt1(at1Var, mb3Var21, yn2Var);
        this.T1 = new ke1(yd1Var);
        this.U1 = new o71(m71Var, mb3Var22);
        mb3 wq1Var = new wq1(this.S, yn2Var);
        this.V1 = wq1Var instanceof db3 ? wq1Var : new db3(wq1Var);
        this.W1 = new it1(at1Var, this.B, yn2Var);
        this.X1 = new fe1(yd1Var);
        this.Y1 = new q71(m71Var, this.k0);
        mb3 yq1Var = new yq1(this.S, yn2Var);
        this.Z1 = yq1Var instanceof db3 ? yq1Var : new db3(yq1Var);
        this.a2 = new ht1(at1Var, this.B, yn2Var);
        this.b2 = new le1(yd1Var);
        this.c2 = new oe1(yd1Var);
        this.d2 = new ue1(yd1Var);
        mb3 p71Var = new p71(m71Var, this.k0);
        this.e2 = p71Var instanceof db3 ? p71Var : new db3(p71Var);
        mb3 ar1Var = new ar1(this.S, yn2Var);
        this.f2 = ar1Var instanceof db3 ? ar1Var : new db3(ar1Var);
        mb3 gs1Var = new gs1(this.U, yn2Var, this.V);
        this.g2 = gs1Var instanceof db3 ? gs1Var : new db3(gs1Var);
        this.h2 = new et1(at1Var, this.B, yn2Var);
        this.i2 = new ne1(yd1Var);
        this.j2 = new ee1(yd1Var);
        mb3 tx1Var = new tx1(this.X0, yn2Var);
        this.k2 = tx1Var instanceof db3 ? tx1Var : new db3(tx1Var);
        this.l2 = new gt1(at1Var, this.B, yn2Var);
        this.m2 = new qe1(yd1Var);
        lb3 lb3VarA8 = jb3.a(0, 2);
        lb3VarA8.b.add(this.l2);
        lb3VarA8.b.add(this.m2);
        jb3 jb3VarA7 = lb3VarA8.a();
        this.n2 = jb3VarA7;
        mb3 nd1Var = new nd1(jb3VarA7);
        this.o2 = nd1Var instanceof db3 ? nd1Var : new db3(nd1Var);
        this.p2 = new de1(yd1Var);
        this.q2 = new ve1(yd1Var);
        this.r2 = new ie1(yd1Var);
        this.s2 = new te1(yd1Var);
        this.t2 = new re1(yd1Var);
        this.u2 = new me1(yd1Var);
        lb3 lb3VarA9 = jb3.a(0, 1);
        lb3VarA9.b.add(this.u2);
        jb3 jb3VarA8 = lb3VarA9.a();
        this.v2 = jb3VarA8;
        mb3 tb1Var = new tb1(jb3VarA8);
        this.w2 = tb1Var instanceof db3 ? tb1Var : new db3(tb1Var);
    }

    @Override // defpackage.ji1
    public final xj1 a(v61 v61Var, jk1 jk1Var, am1 am1Var) {
        return new sz0(this, v61Var, jk1Var, am1Var, null);
    }

    @Override // defpackage.ji1
    public final yj1 b(v61 v61Var, jk1 jk1Var, xi1 xi1Var) {
        return new tz0(this, v61Var, jk1Var, xi1Var, null);
    }

    @Override // defpackage.ji1
    public final h71<l61> c() {
        gv1 gv1Var = new gv1(e(), fz0.a(this.x2.b), r91.a(this.b), yn2.a());
        ll2 ll2VarA = r91.a(this.b);
        zo2 zo2Var = this.I.get();
        t11 t11Var = new t11(rt2.b("setAppMeasurementNPA", new a21(pz0.A(this.x2))), rt2.a("setCookie", new c21(this.J.get()), "setRenderInBrowser", new b21(this.x2.Z.get()), "contentUrlOptedOutSetting", this.L.get(), "contentVerticalOptedOutSetting", new z11(f()), "setAppMeasurementConsentConfig", new y11(e())));
        c32 c32VarR1 = c50.r1(this.I.get(), this.O.get(), this.a1.get(), this.c1.get(), this.x2.L.get(), (k61) this.B1.get(), yn2.a(), this.x2.m.get(), this.N.get());
        md1 md1Var = this.E1.get();
        hl2 hl2Var = this.c;
        bw1 bw1Var = new bw1(yn2.a(), new pv1(uy0.a(this.x2.b)), db3.b(this.F1));
        zo2 zo2Var2 = this.I.get();
        zzbar zzbarVarA = fz0.a(this.x2.b);
        ApplicationInfo applicationInfoA = lu1.a(this.J.get());
        String packageName = e().getPackageName();
        Objects.requireNonNull(packageName, "Cannot return null from a non-@Nullable @Provides method");
        List<String> listB = y40.b();
        PackageInfo packageInfo = this.a0.get();
        xa3 xa3VarB = db3.b(this.b0);
        f();
        g91 g91Var = new g91(zo2Var2, zzbarVarA, applicationInfoA, packageName, listB, packageInfo, xa3VarB, this.m.get(), new pd2(yn2.a(), qt2.s(new ub2(yn2.a(), r91.a(this.b), this.a0.get(), f()), new hb2(this.x2.T.get(), this.d.a, this.J.get(), g()), new t92(p91.a(this.k0.get()), this.x2.w.get(), this.k0.get(), this.P.get(), r91.a(this.b)), new w82(this.x2.V.get(), r91.a(this.b), e(), this.x2.R.get()), new r82(r91.a(this.b)), new zb2(this.x2.T.get(), e(), g()), new e92(this.x2.T.get(), this.x2.s.get(), this.x2.D.get(), this.x2.W.get()), new za2(this.J.get(), yn2.a()), new b92(g()), new hc2(yn2.a(), this.b.c), new ta2(e(), yn2.a()), new gc2(lu1.a(this.J.get()), this.a0.get()), new fd2(this.f), new o92(yn2.a(), r91.a(this.b), fz0.a(this.x2.b)), new x92(yn2.a(), e()), new t82(this.A0.get(), yn2.a()), new ad2(yn2.a(), e(), fz0.a(this.x2.b)), this.x2.V.get(), new ae2(yn2.a(), e()), this.x2.Y.get(), new mb2(yn2.a()), new wc2(this.x2.E.get(), yn2.a(), e()), new db2(yn2.a()), new qb2(yn2.a(), this.x2.Z.get()), new p92(yn2.a(), this.x2.R.get()), new rc2(yn2.a(), this.x2.m.get(), "native", this.x2.u.get(), this.J.get(), r91.a(this.b), this.J0.get()), new gd2(yn2.a(), e()), new ga2(this.g), new mc2(this.m.get(), this.O0.get()), new na2(yn2.a(), this.x2.F.get(), r91.a(this.b), "native"))));
        zv2 zv2VarA = yn2.a();
        rt2 rt2VarB = rt2.b("Network", this.I1);
        zv2 zv2VarA2 = yn2.a();
        tt2 tt2VarZ = qt2.z(7);
        tt2VarZ.a(c50.q1(this.k0.get()));
        tt2VarZ.a(this.J1.get());
        tt2VarZ.a(this.L1.get());
        tt2VarZ.a(this.M1.get());
        tt2VarZ.d(c50.b3(this.B.get(), yn2.a()));
        tt2VarZ.d(c50.H4(this.j));
        tt2VarZ.a(this.O1.get());
        return c50.p1(gv1Var, ll2VarA, zo2Var, t11Var, c32VarR1, md1Var, hl2Var, bw1Var, g91Var, zv2VarA, new uv1(rt2VarB, zv2VarA2, new nc1(tt2VarZ.e())), this.N.get());
    }

    @Override // defpackage.ji1
    public final ba1 d() {
        return this.a1.get();
    }

    public final Context e() {
        return uy0.a(this.x2.b);
    }

    public final zzf f() {
        return lm2.a(this.x2.R.get());
    }

    public final Set<String> g() {
        tt2 tt2VarZ = qt2.z(2);
        tt2VarZ.d(li1.a(hi1.a(this.e)));
        tt2 tt2Var = tt2VarZ;
        tt2Var.a("native");
        return tt2Var.e();
    }
}
