package defpackage;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import com.google.android.gms.ads.VideoController;
import com.google.android.gms.ads.doubleclick.AppEventListener;
import com.google.android.gms.ads.internal.overlay.zzp;
import com.google.android.gms.ads.internal.util.zzf;
import com.google.android.gms.ads.reward.AdMetadataListener;
import com.google.android.gms.internal.ads.zzbar;
import defpackage.lp3;
import defpackage.n91;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.Executor;

/* loaded from: classes.dex */
public final class s01 extends gp1 {
    public mb3<Set<sf1<da1>>> A;
    public mb3<i52> A0;
    public mb3<sf1<sc1>> A1;
    public mb3<Set<sf1<da1>>> B;
    public mb3<rc2> B0;
    public mb3 B1;
    public mb3<yr1> C;
    public mb3<gd2> C0;
    public mb3<sf1<sc1>> C1;
    public mb3<yr1> D;
    public mb3<vh2> D0;
    public mb3<Set<sf1<ua1>>> D1;
    public mb3<Map<ap2, yr1>> E;
    public mb3<ga2> E0;
    public mb3<Set<sf1<ua1>>> E1;
    public mb3<wr1> F;
    public mb3<String> F0;
    public mb3<sf1<ca1>> F1;
    public mb3<Set<sf1<fp2>>> G;
    public mb3<mc2> G0;
    public mb3<Set<sf1<ca1>>> G1;
    public mb3 H;
    public mb3<na2> H0;
    public mb3<Set<sf1<ca1>>> H1;
    public mb3<rs1> I;
    public mb3<Set<qd2<? extends nd2<Bundle>>>> I0;
    public mb3<kf1> I1;
    public mb3 J;
    public mb3<pd2<Bundle>> J0;
    public mb3<sf1<ca1>> J1;
    public mb3<px1> K;
    public mb3<g91> K0;
    public mb3<sf1<va1>> K1;
    public mb3<sf1<fp2>> L;
    public mb3<vx1> L0;
    public mb3<sf1<va1>> L1;
    public mb3<Set<sf1<fp2>>> M;
    public mb3<xx1> M0;
    public mb3<Set<sf1<va1>>> M1;
    public mb3<dy1> N;
    public mb3<gy1> N0;
    public mb3<Set<sf1<va1>>> N1;
    public mb3<ey1> O;
    public mb3<by1> O0;
    public mb3<Set<sf1<hc1>>> O1;
    public mb3<sf1<fp2>> P;
    public mb3<sf1<da1>> P0;
    public mb3<sf1<er3>> P1;
    public mb3<Set<sf1<fp2>>> Q;
    public mb3<Set<sf1<da1>>> Q0;
    public mb3<sf1<er3>> Q1;
    public mb3 R;
    public mb3<ba1> R0;
    public mb3<Set<sf1<er3>>> R1;
    public mb3<zo2> S;
    public mb3<x11> S0;
    public mb3<Set<sf1<er3>>> S1;
    public mb3<Context> T;
    public mb3<x22> T0;
    public mb3<Set<sf1<xf1>>> T1;
    public mb3<ApplicationInfo> U;
    public mb3<nz1> U0;
    public mb3<sf1<ob1>> U1;
    public mb3<PackageInfo> V;
    public mb3<v22> V0;
    public mb3<sf1<ob1>> V1;
    public mb3<aw2<String>> W;
    public mb3<gl2> W0;
    public mb3<sf1<ob1>> W1;
    public mb3<zzf> X;
    public mb3<hq2> X0;
    public mb3<Set<sf1<ob1>>> X1;
    public mb3<nr0> Y;
    public mb3<gp1> Y0;
    public mb3<Set<sf1<ob1>>> Y1;
    public mb3<t71> Z;
    public mb3<w32> Z0;
    public mb3<Set<sf1<ob1>>> Z1;
    public final im2 a;
    public mb3<String> a0;
    public mb3<g42<dp1, zl2, f12>> a1;
    public mb3<sf1<ob1>> a2;
    public final n91 b;
    public mb3<t92> b0;
    public mb3<d32> b1;
    public mb3<Set<sf1<AppEventListener>>> b2;
    public final hl2 c;
    public mb3<w82> c0;
    public mb3<g42<dp1, zl2, g12>> c1;
    public mb3<Set<sf1<AppEventListener>>> c2;
    public final si2 d;
    public mb3<r82> d0;
    public mb3<jz1<dp1>> d1;
    public mb3<Set<sf1<AppEventListener>>> d2;
    public final vh2 e;
    public mb3<String> e0;
    public mb3<g32> e1;
    public mb3<ld1> e2;
    public final m71 f;
    public mb3<Set<String>> f0;
    public mb3<c42> f1;
    public mb3<Set<sf1<zzp>>> f2;
    public final at1 g;
    public mb3<zb2> g0;
    public mb3<jz1<dp1>> g1;
    public mb3<Set<sf1<VideoController.VideoLifecycleCallbacks>>> g2;
    public final yd1 h;
    public mb3<e92> h0;
    public mb3<b60> h1;
    public mb3<Set<sf1<ra1>>> h2;
    public mb3<Context> i;
    public mb3<za2> i0;
    public mb3<kc1> i1;
    public mb3<Set<sf1<AdMetadataListener>>> i2;
    public mb3<xr0> j;
    public mb3 j0;
    public mb3<mp1> j1;
    public mb3<Set<sf1<AdMetadataListener>>> j2;
    public mb3<gm2> k;
    public mb3<Bundle> k0;
    public mb3<m32> k1;
    public mb3<rb1> k2;
    public mb3<sf1<da1>> l;
    public mb3<hc2> l0;
    public mb3<n91.a> l1;
    public mb3<Set<sf1<em3>>> l2;
    public mb3<String> m;
    public mb3<ta2> m0;
    public mb3<yd1> m1;
    public mb3<Set<sf1<ed1>>> m2;
    public mb3<ll2> n;
    public mb3<gc2> n0;
    public mb3<t22> n1;
    public final /* synthetic */ pz0 n2;
    public mb3<lp3.a> o;
    public mb3<fd2> o0;
    public mb3<Map<String, jz1<dp1>>> o1;
    public mb3<String> p;
    public mb3<o92> p0;
    public mb3<j61<dp1>> p1;
    public mb3<ep3> q;
    public mb3<x92> q0;
    public mb3<sf1<ud1>> q1;
    public mb3<si2> r;
    public mb3<aw2<String>> r0;
    public mb3<Set<sf1<ud1>>> r1;
    public mb3<fr1> s;
    public mb3<t82> s0;
    public mb3<md1> s1;
    public mb3<sf1<da1>> t;
    public mb3<ad2> t0;
    public mb3<mw1> t1;
    public mb3<ks1> u;
    public mb3<ae2> u0;
    public mb3<kv1> u1;
    public mb3<cs1> v;
    public mb3<mb2> v0;
    public mb3<au1> v1;
    public mb3<qp2> w;
    public mb3<wc2> w0;
    public mb3<zu1> w1;
    public mb3<ix1> x;
    public mb3<db2> x0;
    public mb3<sf1<sc1>> x1;
    public mb3<sf1<da1>> y;
    public mb3<qb2> y0;
    public mb3<u81> y1;
    public mb3<jt1> z;
    public mb3<p92> z0;
    public mb3<sf1<sc1>> z1;

    public s01(pz0 pz0Var, m71 m71Var, em2 em2Var, w81 w81Var, at1 at1Var, yd1 yd1Var, n91 n91Var, im2 im2Var, hl2 hl2Var, si2 si2Var, vh2 vh2Var, oz0 oz0Var) {
        this.n2 = pz0Var;
        this.a = im2Var;
        this.b = n91Var;
        this.c = hl2Var;
        this.d = si2Var;
        this.e = vh2Var;
        this.f = m71Var;
        this.g = at1Var;
        this.h = yd1Var;
        km2 km2Var = new km2(im2Var, pz0Var.g);
        this.i = km2Var;
        nm2 nm2Var = new nm2(im2Var, pz0Var.R);
        this.j = nm2Var;
        mb3 jm2Var = new jm2(km2Var, nm2Var);
        Object obj = db3.c;
        jm2Var = jm2Var instanceof db3 ? jm2Var : new db3(jm2Var);
        this.k = jm2Var;
        this.l = new hm2(em2Var, jm2Var);
        this.m = new ru1(this.i);
        r91 r91Var = new r91(n91Var);
        this.n = r91Var;
        this.o = new lp1(r91Var);
        mb3 db3Var = wu1.a;
        db3Var = db3Var instanceof db3 ? db3Var : new db3(db3Var);
        this.p = db3Var;
        mb3 mb3VarA = tq1.a(pz0Var.g, this.m, pz0Var.h, this.o, db3Var);
        this.q = mb3VarA instanceof db3 ? mb3VarA : new db3(mb3VarA);
        cb3 cb3VarB = fb3.b(si2Var);
        this.r = cb3VarB;
        mb3 mr1Var = new mr1(this.q, cb3VarB);
        mr1Var = mr1Var instanceof db3 ? mr1Var : new db3(mr1Var);
        this.s = mr1Var;
        yn2 yn2Var = bo2.a;
        mb3 vq1Var = new vq1(mr1Var, yn2Var);
        this.t = vq1Var instanceof db3 ? vq1Var : new db3(vq1Var);
        mb3 js1Var = new js1(pz0Var.x, this.j);
        js1Var = js1Var instanceof db3 ? js1Var : new db3(js1Var);
        this.u = js1Var;
        mb3 bs1Var = new bs1(js1Var, pz0Var.x);
        this.v = bs1Var instanceof db3 ? bs1Var : new db3(bs1Var);
        mb3 vu1Var = new vu1(this.p);
        vu1Var = vu1Var instanceof db3 ? vu1Var : new db3(vu1Var);
        this.w = vu1Var;
        mb3 hx1Var = new hx1(vu1Var, pz0Var.n, this.j);
        hx1Var = hx1Var instanceof db3 ? hx1Var : new db3(hx1Var);
        this.x = hx1Var;
        mb3 ds1Var = new ds1(this.v, yn2Var, hx1Var);
        this.y = ds1Var instanceof db3 ? ds1Var : new db3(ds1Var);
        mb3 nt1Var = new nt1(pz0Var.S, pz0Var.H);
        nt1Var = nt1Var instanceof db3 ? nt1Var : new db3(nt1Var);
        this.z = nt1Var;
        this.A = new ct1(at1Var, nt1Var, yn2Var);
        this.B = new je1(yd1Var);
        mb3 mb3Var = br1.a;
        this.C = mb3Var instanceof db3 ? mb3Var : new db3(mb3Var);
        mb3 mb3Var2 = dr1.a;
        this.D = mb3Var2 instanceof db3 ? mb3Var2 : new db3(mb3Var2);
        gb3 gb3VarA = eb3.a(2);
        ap2 ap2Var = ap2.SIGNALS;
        mb3<yr1> mb3Var3 = this.C;
        LinkedHashMap<K, mb3<V>> linkedHashMap = gb3VarA.a;
        Objects.requireNonNull(mb3Var3, "provider");
        linkedHashMap.put(ap2Var, mb3Var3);
        ap2 ap2Var2 = ap2.RENDERER;
        mb3<yr1> mb3Var4 = this.D;
        LinkedHashMap<K, mb3<V>> linkedHashMap2 = gb3VarA.a;
        Objects.requireNonNull(mb3Var4, "provider");
        linkedHashMap2.put(ap2Var2, mb3Var4);
        eb3 eb3VarA = gb3VarA.a();
        this.E = eb3VarA;
        xr1 xr1Var = new xr1(this.q, eb3VarA);
        this.F = xr1Var;
        mb3 gr1Var = new gr1(yn2Var, xr1Var);
        this.G = gr1Var instanceof db3 ? gr1Var : new db3(gr1Var);
        lb3 lb3VarA = jb3.a(1, 0);
        lb3VarA.a.add(hs1.a);
        jb3 jb3VarA = lb3VarA.a();
        this.H = jb3VarA;
        mb3 ts1Var = new ts1(this.u, jb3VarA, pz0Var.q);
        this.I = ts1Var instanceof db3 ? ts1Var : new db3(ts1Var);
        lb3 lb3VarA2 = jb3.a(1, 0);
        lb3VarA2.a.add(mx1.a);
        jb3 jb3VarA2 = lb3VarA2.a();
        this.J = jb3VarA2;
        mb3 rx1Var = new rx1(jb3VarA2, this.w);
        rx1Var = rx1Var instanceof db3 ? rx1Var : new db3(rx1Var);
        this.K = rx1Var;
        mb3 fs1Var = new fs1(this.I, yn2Var, rx1Var);
        this.L = fs1Var instanceof db3 ? fs1Var : new db3(fs1Var);
        this.M = new kt1(at1Var, this.z, yn2Var);
        mb3 db3Var2 = fy1.a;
        db3Var2 = db3Var2 instanceof db3 ? db3Var2 : new db3(db3Var2);
        this.N = db3Var2;
        hy1 hy1Var = new hy1(db3Var2);
        this.O = hy1Var;
        mb3 sx1Var = new sx1(hy1Var, yn2Var);
        this.P = sx1Var instanceof db3 ? sx1Var : new db3(sx1Var);
        lb3 lb3VarA3 = jb3.a(2, 2);
        lb3VarA3.b.add(this.G);
        lb3VarA3.a.add(this.L);
        lb3VarA3.b.add(this.M);
        lb3VarA3.a.add(this.P);
        jb3 jb3VarA3 = lb3VarA3.a();
        this.Q = jb3VarA3;
        hp2 hp2Var = new hp2(jb3VarA3);
        this.R = hp2Var;
        mb3 ip2Var = new ip2(yn2Var, pz0Var.m, hp2Var);
        this.S = ip2Var instanceof db3 ? ip2Var : new db3(ip2Var);
        mb3 o91Var = new o91(n91Var, this.i);
        o91Var = o91Var instanceof db3 ? o91Var : new db3(o91Var);
        this.T = o91Var;
        lu1 lu1Var = new lu1(o91Var);
        this.U = lu1Var;
        mb3 su1Var = new su1(o91Var, lu1Var);
        this.V = su1Var instanceof db3 ? su1Var : new db3(su1Var);
        mb3 ju1Var = new ju1(this.S, this.T);
        this.W = ju1Var instanceof db3 ? ju1Var : new db3(ju1Var);
        this.X = new lm2(im2Var, pz0Var.R);
        mb3 r71Var = new r71(pz0Var.q, this.j, this.n);
        r71Var = r71Var instanceof db3 ? r71Var : new db3(r71Var);
        this.Y = r71Var;
        mb3 s71Var = new s71(pz0Var.q, r71Var);
        s71Var = s71Var instanceof db3 ? s71Var : new db3(s71Var);
        this.Z = s71Var;
        p91 p91Var = new p91(n91Var, s71Var);
        this.a0 = p91Var;
        this.b0 = v92.a(p91Var, pz0Var.w, s71Var, this.k, this.n);
        mb3<ha2<td2>> mb3Var5 = pz0Var.V;
        mb3<ll2> mb3Var6 = this.n;
        this.c0 = new y82(mb3Var5, mb3Var6, this.i, pz0Var.R);
        this.d0 = new q82(mb3Var6);
        this.e0 = new kp1(mb3Var6);
        lb3 lb3VarA4 = jb3.a(1, 0);
        lb3VarA4.a.add(this.e0);
        jb3 jb3VarA4 = lb3VarA4.a();
        this.f0 = jb3VarA4;
        mb3<zv2> mb3Var7 = pz0Var.T;
        mb3<Context> mb3Var8 = this.i;
        this.g0 = new bc2(mb3Var7, mb3Var8, jb3VarA4);
        this.h0 = new m92(mb3Var7, pz0Var.s, pz0Var.D, pz0Var.W);
        this.i0 = new bb2(this.T, yn2Var);
        this.j0 = new d92(jb3VarA4);
        q91 q91Var = new q91(n91Var);
        this.k0 = q91Var;
        this.l0 = new jc2(yn2Var, q91Var);
        this.m0 = new xa2(mb3Var8, yn2Var);
        this.n0 = new fc2(this.U, this.V);
        this.o0 = new hd2(this.r);
        this.p0 = new q92(yn2Var, this.n, pz0Var.h);
        mb3<Context> mb3Var9 = this.i;
        this.q0 = new z92(yn2Var, mb3Var9);
        mb3 ku1Var = new ku1(pz0Var.I, mb3Var9, yn2Var);
        ku1Var = ku1Var instanceof db3 ? ku1Var : new db3(ku1Var);
        this.r0 = ku1Var;
        this.s0 = new u82(ku1Var, yn2Var);
        mb3<Context> mb3Var10 = this.i;
        this.t0 = new cd2(yn2Var, mb3Var10, pz0Var.h);
        this.u0 = new ce2(yn2Var, mb3Var10);
        this.v0 = new ob2(yn2Var);
        this.w0 = new yc2(pz0Var.E, yn2Var, mb3Var10);
        this.x0 = new fb2(yn2Var);
        this.y0 = new sb2(yn2Var, pz0Var.Z);
        this.z0 = new u92(yn2Var, pz0Var.R);
        h52 h52Var = new h52(pz0Var.s);
        mb3<i52> db3Var3 = h52Var instanceof db3 ? h52Var : new db3<>(h52Var);
        this.A0 = db3Var3;
        this.B0 = uc2.a(yn2Var, pz0Var.m, this.e0, pz0Var.u, this.T, this.n, db3Var3);
        this.C0 = new od2(yn2Var, this.i);
        cb3 cb3VarB2 = fb3.b(vh2Var);
        this.D0 = cb3VarB2;
        this.E0 = new ja2(cb3VarB2);
        mb3 db3Var4 = pu1.a;
        db3Var4 = db3Var4 instanceof db3 ? db3Var4 : new db3(db3Var4);
        this.F0 = db3Var4;
        this.G0 = new pc2(this.p, db3Var4);
        this.H0 = new pa2(yn2Var, pz0Var.F, this.n, this.e0);
        lb3 lb3VarA5 = jb3.a(28, 0);
        lb3VarA5.a.add(this.b0);
        lb3VarA5.a.add(this.c0);
        lb3VarA5.a.add(this.d0);
        lb3VarA5.a.add(this.g0);
        lb3VarA5.a.add(this.h0);
        lb3VarA5.a.add(this.i0);
        lb3VarA5.a.add(this.j0);
        lb3VarA5.a.add(this.l0);
        lb3VarA5.a.add(this.m0);
        lb3VarA5.a.add(this.n0);
        lb3VarA5.a.add(this.o0);
        lb3VarA5.a.add(this.p0);
        lb3VarA5.a.add(this.q0);
        lb3VarA5.a.add(this.s0);
        lb3VarA5.a.add(this.t0);
        lb3VarA5.a.add(pz0Var.V);
        lb3VarA5.a.add(this.u0);
        lb3VarA5.a.add(pz0Var.Y);
        lb3VarA5.a.add(this.v0);
        lb3VarA5.a.add(this.w0);
        lb3VarA5.a.add(this.x0);
        lb3VarA5.a.add(this.y0);
        lb3VarA5.a.add(this.z0);
        lb3VarA5.a.add(this.B0);
        lb3VarA5.a.add(this.C0);
        lb3VarA5.a.add(this.E0);
        lb3VarA5.a.add(this.G0);
        lb3VarA5.a.add(this.H0);
        jb3 jb3VarA5 = lb3VarA5.a();
        this.I0 = jb3VarA5;
        ud2 ud2Var = new ud2(yn2Var, jb3VarA5);
        this.J0 = ud2Var;
        i91 i91VarA = i91.a(this.S, pz0Var.h, this.U, this.m, nu1.a, this.V, this.W, this.X, this.p, ud2Var);
        this.K0 = i91VarA;
        mb3<Context> mb3Var11 = this.i;
        ux1 ux1Var = new ux1(mb3Var11);
        this.L0 = ux1Var;
        yx1 yx1Var = new yx1(ux1Var, pz0Var.p);
        this.M0 = yx1Var;
        ky1 ky1VarA = ky1.a(mb3Var11, i91VarA, this.N, yx1Var, this.X);
        this.N0 = ky1VarA;
        mb3 ay1Var = new ay1(ky1VarA, this.X);
        ay1Var = ay1Var instanceof db3 ? ay1Var : new db3(ay1Var);
        this.O0 = ay1Var;
        mb3 qx1Var = new qx1(ay1Var, yn2Var);
        this.P0 = qx1Var instanceof db3 ? qx1Var : new db3(qx1Var);
        lb3 lb3VarA6 = jb3.a(4, 2);
        lb3VarA6.a.add(this.l);
        lb3VarA6.a.add(this.t);
        lb3VarA6.a.add(this.y);
        lb3VarA6.b.add(this.A);
        lb3VarA6.b.add(this.B);
        lb3VarA6.a.add(this.P0);
        jb3 jb3VarA6 = lb3VarA6.a();
        this.Q0 = jb3VarA6;
        mb3 ce1Var = new ce1(yd1Var, jb3VarA6);
        this.R0 = ce1Var instanceof db3 ? ce1Var : new db3(ce1Var);
        mb3 w11Var = new w11(this.X);
        this.S0 = w11Var instanceof db3 ? w11Var : new db3(w11Var);
        this.T0 = new a32(pz0Var.a0, pz0Var.r, pz0Var.M, pz0Var.n);
        mb3 db3Var5 = pz1.a;
        db3Var5 = db3Var5 instanceof db3 ? db3Var5 : new db3(db3Var5);
        this.U0 = db3Var5;
        we1 we1Var = new we1(yd1Var, pz0Var.q, this.T0, db3Var5);
        mb3<v22> db3Var6 = we1Var instanceof db3 ? we1Var : new db3<>(we1Var);
        this.V0 = db3Var6;
        s91 s91Var = new s91(n91Var);
        this.W0 = s91Var;
        mb3 mb3VarA2 = gq2.a(db3Var6, pz0Var.h, this.a0, pz0Var.w, this.T, s91Var, pz0Var.q, pz0Var.I);
        this.X0 = mb3VarA2 instanceof db3 ? mb3VarA2 : new db3(mb3VarA2);
        fb3 fb3Var = new fb3(this);
        this.Y0 = fb3Var;
        mb3<Context> mb3Var12 = this.T;
        mb3<Executor> mb3Var13 = pz0Var.o;
        d42 d42Var = new d42(mb3Var12, mb3Var13, fb3Var);
        this.Z0 = d42Var;
        mb3<zo2> mb3Var14 = this.S;
        mb3<zv2> mb3Var15 = pz0Var.T;
        k42 k42Var = new k42(mb3Var14, mb3Var15, pz0Var.t, d42Var);
        this.a1 = k42Var;
        e32 e32Var = new e32(mb3Var12, mb3Var13, fb3Var);
        this.b1 = e32Var;
        k42 k42Var2 = new k42(mb3Var14, mb3Var15, pz0Var.b0, e32Var);
        this.c1 = k42Var2;
        this.d1 = new jp1(k42Var, k42Var2, this.n);
        h32 h32Var = new h32(mb3Var12, this.Y0);
        this.e1 = h32Var;
        f42 f42Var = new f42(this.A0);
        this.f1 = f42Var;
        this.g1 = new np1(this.S, pz0Var.T, h32Var, f42Var);
        mb3 mb3Var16 = d60.a;
        mb3 db3Var7 = mb3Var16 instanceof db3 ? mb3Var16 : new db3(mb3Var16);
        this.h1 = db3Var7;
        f91 f91Var = new f91(pz0Var.j0);
        this.i1 = f91Var;
        mb3 mb3VarA3 = aq1.a(h11.a, this.T, pz0Var.I, db3Var7, pz0Var.h, pz0Var.J, this.q, f91Var);
        mb3VarA3 = mb3VarA3 instanceof db3 ? mb3VarA3 : new db3(mb3VarA3);
        this.j1 = mb3VarA3;
        this.k1 = new x32(this.T, pz0Var.h, this.n, pz0Var.o, this.Y0, mb3VarA3, qb0.a);
        u91 u91Var = new u91(n91Var);
        this.l1 = u91Var;
        se1 se1Var = new se1(yd1Var);
        this.m1 = se1Var;
        this.n1 = new w22(pz0Var.H, u91Var, se1Var);
        gb3 gb3VarA2 = eb3.a(4);
        mb3<jz1<dp1>> mb3Var17 = this.d1;
        LinkedHashMap<K, mb3<V>> linkedHashMap3 = gb3VarA2.a;
        Objects.requireNonNull(mb3Var17, "provider");
        linkedHashMap3.put("ThirdPartyRenderer", mb3Var17);
        mb3<jz1<dp1>> mb3Var18 = this.g1;
        LinkedHashMap<K, mb3<V>> linkedHashMap4 = gb3VarA2.a;
        Objects.requireNonNull(mb3Var18, "provider");
        linkedHashMap4.put("RtbRendererRewarded", mb3Var18);
        mb3<m32> mb3Var19 = this.k1;
        LinkedHashMap<K, mb3<V>> linkedHashMap5 = gb3VarA2.a;
        Objects.requireNonNull(mb3Var19, "provider");
        linkedHashMap5.put("FirstPartyRenderer", mb3Var19);
        mb3<t22> mb3Var20 = this.n1;
        LinkedHashMap<K, mb3<V>> linkedHashMap6 = gb3VarA2.a;
        Objects.requireNonNull(mb3Var20, "provider");
        linkedHashMap6.put("RecursiveRenderer", mb3Var20);
        eb3 eb3VarA2 = gb3VarA2.a();
        this.o1 = eb3VarA2;
        mb3 m61Var = new m61(eb3VarA2);
        this.p1 = m61Var instanceof db3 ? m61Var : new db3(m61Var);
        mb3 xq1Var = new xq1(this.s, yn2Var);
        this.q1 = xq1Var instanceof db3 ? xq1Var : new db3(xq1Var);
        lb3 lb3VarA7 = jb3.a(1, 0);
        lb3VarA7.a.add(this.q1);
        jb3 jb3VarA7 = lb3VarA7.a();
        this.r1 = jb3VarA7;
        mb3 vd1Var = new vd1(jb3VarA7);
        this.s1 = vd1Var instanceof db3 ? vd1Var : new db3(vd1Var);
        cx1 cx1VarA = cx1.a(pz0Var.g, pz0Var.o, nz0.a, pz0Var.c0, pz0Var.d0, pz0Var.e0);
        this.t1 = cx1VarA;
        uu1 uu1Var = new uu1(this.T);
        this.u1 = uu1Var;
        eu1 eu1Var = new eu1(fo2.a, yn2Var, uu1Var, cx1VarA);
        this.v1 = eu1Var;
        this.w1 = dv1.a(this.n, eu1Var, yn2Var, pz0Var.m, this.N);
        mb3 zq1Var = new zq1(this.s, yn2Var);
        this.x1 = zq1Var instanceof db3 ? zq1Var : new db3(zq1Var);
        mb3 mb3VarA4 = t81.a(this.i, this.n, pz0Var.h, this.X, pz0Var.D);
        mb3VarA4 = mb3VarA4 instanceof db3 ? mb3VarA4 : new db3(mb3VarA4);
        this.y1 = mb3VarA4;
        mb3 v81Var = new v81(w81Var, mb3VarA4);
        this.z1 = v81Var instanceof db3 ? v81Var : new db3(v81Var);
        mb3 es1Var = new es1(this.v, yn2Var, this.x);
        this.A1 = es1Var instanceof db3 ? es1Var : new db3(es1Var);
        vv1 vv1Var = new vv1(this.i, pz0Var.E);
        this.B1 = vv1Var;
        mb3 mu1Var = new mu1(vv1Var, yn2Var);
        this.C1 = mu1Var instanceof db3 ? mu1Var : new db3(mu1Var);
        mb3<jt1> mb3Var21 = this.z;
        this.D1 = new ft1(at1Var, mb3Var21, yn2Var);
        this.E1 = new be1(yd1Var);
        this.F1 = new n71(m71Var, this.Z);
        this.G1 = new dt1(at1Var, mb3Var21, yn2Var);
        this.H1 = new ke1(yd1Var);
        mb3 db3Var8 = mf1.a;
        db3Var8 = db3Var8 instanceof db3 ? db3Var8 : new db3(db3Var8);
        this.I1 = db3Var8;
        this.J1 = new ip1(db3Var8);
        this.K1 = new q71(m71Var, this.Z);
        mb3 yq1Var = new yq1(this.s, yn2Var);
        this.L1 = yq1Var instanceof db3 ? yq1Var : new db3(yq1Var);
        this.M1 = new ht1(at1Var, this.z, yn2Var);
        this.N1 = new le1(yd1Var);
        this.O1 = new oe1(yd1Var);
        this.P1 = new o71(m71Var, this.Z);
        mb3 wq1Var = new wq1(this.s, yn2Var);
        this.Q1 = wq1Var instanceof db3 ? wq1Var : new db3(wq1Var);
        this.R1 = new it1(at1Var, this.z, yn2Var);
        this.S1 = new fe1(yd1Var);
        this.T1 = new ue1(yd1Var);
        mb3 p71Var = new p71(m71Var, this.Z);
        this.U1 = p71Var instanceof db3 ? p71Var : new db3(p71Var);
        mb3 ar1Var = new ar1(this.s, yn2Var);
        this.V1 = ar1Var instanceof db3 ? ar1Var : new db3(ar1Var);
        mb3 gs1Var = new gs1(this.v, yn2Var, this.x);
        this.W1 = gs1Var instanceof db3 ? gs1Var : new db3(gs1Var);
        this.X1 = new et1(at1Var, this.z, yn2Var);
        this.Y1 = new ne1(yd1Var);
        this.Z1 = new ee1(yd1Var);
        mb3 tx1Var = new tx1(this.O0, yn2Var);
        this.a2 = tx1Var instanceof db3 ? tx1Var : new db3(tx1Var);
        this.b2 = new gt1(at1Var, this.z, yn2Var);
        this.c2 = new qe1(yd1Var);
        lb3 lb3VarA8 = jb3.a(0, 2);
        lb3VarA8.b.add(this.b2);
        lb3VarA8.b.add(this.c2);
        jb3 jb3VarA8 = lb3VarA8.a();
        this.d2 = jb3VarA8;
        mb3 nd1Var = new nd1(jb3VarA8);
        this.e2 = nd1Var instanceof db3 ? nd1Var : new db3(nd1Var);
        this.f2 = new de1(yd1Var);
        this.g2 = new ve1(yd1Var);
        this.h2 = new ie1(yd1Var);
        this.i2 = new me1(yd1Var);
        lb3 lb3VarA9 = jb3.a(0, 1);
        lb3VarA9.b.add(this.i2);
        jb3 jb3VarA9 = lb3VarA9.a();
        this.j2 = jb3VarA9;
        mb3 tb1Var = new tb1(jb3VarA9);
        this.k2 = tb1Var instanceof db3 ? tb1Var : new db3(tb1Var);
        this.l2 = new re1(yd1Var);
        this.m2 = new ge1(yd1Var);
    }

    @Override // defpackage.gp1
    public final ba1 a() {
        return this.R0.get();
    }

    @Override // defpackage.l91
    public final ll2 b() {
        return r91.a(this.b);
    }

    @Override // defpackage.l91
    public final mi2 c() {
        return this.h.m;
    }

    @Override // defpackage.gp1, defpackage.l91
    public final h71<dp1> d() {
        gv1 gv1Var = new gv1(f(), fz0.a(this.n2.b), r91.a(this.b), yn2.a());
        ll2 ll2VarA = r91.a(this.b);
        zo2 zo2Var = this.S.get();
        t11 t11Var = new t11(rt2.b("setAppMeasurementNPA", new a21(pz0.A(this.n2))), rt2.a("setCookie", new c21(this.T.get()), "setRenderInBrowser", new b21(this.n2.Z.get()), "contentUrlOptedOutSetting", this.S0.get(), "contentVerticalOptedOutSetting", new z11(lm2.a(this.n2.R.get())), "setAppMeasurementConsentConfig", new y11(f())));
        c32 c32VarR1 = c50.r1(this.S.get(), this.V0.get(), this.R0.get(), this.X0.get(), this.n2.L.get(), this.p1.get(), yn2.a(), this.n2.m.get(), this.U0.get());
        md1 md1Var = this.s1.get();
        hl2 hl2Var = this.c;
        bw1 bw1Var = new bw1(yn2.a(), new pv1(uy0.a(this.n2.b)), db3.b(this.t1));
        zo2 zo2Var2 = this.S.get();
        zzbar zzbarVarA = fz0.a(this.n2.b);
        ApplicationInfo applicationInfoA = lu1.a(this.T.get());
        String packageName = f().getPackageName();
        Objects.requireNonNull(packageName, "Cannot return null from a non-@Nullable @Provides method");
        List<String> listB = y40.b();
        PackageInfo packageInfo = this.V.get();
        xa3 xa3VarB = db3.b(this.W);
        lm2.a(this.n2.R.get());
        String str = this.p.get();
        zv2 zv2VarA = yn2.a();
        t92 t92Var = new t92(p91.a(this.Z.get()), this.n2.w.get(), this.Z.get(), this.k.get(), r91.a(this.b));
        w82 w82Var = new w82(this.n2.V.get(), r91.a(this.b), f(), this.n2.R.get());
        r82 r82Var = new r82(r91.a(this.b));
        zv2 zv2Var = this.n2.T.get();
        Context contextF = f();
        String strG = g();
        int i = qt2.g;
        g91 g91Var = new g91(zo2Var2, zzbarVarA, applicationInfoA, packageName, listB, packageInfo, xa3VarB, str, new pd2(zv2VarA, qt2.s(t92Var, w82Var, r82Var, new zb2(zv2Var, contextF, new gu2(strG)), new e92(this.n2.T.get(), this.n2.s.get(), this.n2.D.get(), this.n2.W.get()), new za2(this.T.get(), yn2.a()), new b92(new gu2(g())), new hc2(yn2.a(), this.b.c), new ta2(f(), yn2.a()), new gc2(lu1.a(this.T.get()), this.V.get()), new fd2(this.d), new o92(yn2.a(), r91.a(this.b), fz0.a(this.n2.b)), new x92(yn2.a(), f()), new t82(this.r0.get(), yn2.a()), new ad2(yn2.a(), f(), fz0.a(this.n2.b)), this.n2.V.get(), new ae2(yn2.a(), f()), this.n2.Y.get(), new mb2(yn2.a()), new wc2(this.n2.E.get(), yn2.a(), f()), new db2(yn2.a()), new qb2(yn2.a(), this.n2.Z.get()), new p92(yn2.a(), this.n2.R.get()), new rc2(yn2.a(), this.n2.m.get(), g(), this.n2.u.get(), this.T.get(), r91.a(this.b), this.A0.get()), new gd2(yn2.a(), f()), new ga2(this.e), new mc2(this.p.get(), this.F0.get()), new na2(yn2.a(), this.n2.F.get(), r91.a(this.b), g()))));
        zv2 zv2VarA2 = yn2.a();
        rt2 rt2VarB = rt2.b("Network", this.w1);
        zv2 zv2VarA3 = yn2.a();
        tt2 tt2VarZ = qt2.z(7);
        tt2VarZ.a(c50.q1(this.Z.get()));
        tt2VarZ.a(this.x1.get());
        tt2VarZ.a(this.z1.get());
        tt2VarZ.a(this.A1.get());
        tt2VarZ.d(c50.b3(this.z.get(), yn2.a()));
        tt2VarZ.d(c50.H4(this.h));
        tt2VarZ.a(this.C1.get());
        return c50.p1(gv1Var, ll2VarA, zo2Var, t11Var, c32VarR1, md1Var, hl2Var, bw1Var, g91Var, zv2VarA2, new uv1(rt2VarB, zv2VarA3, new nc1(tt2VarZ.e())), this.U0.get());
    }

    @Override // defpackage.gp1
    public final fp1 e(v61 v61Var, ep1 ep1Var) {
        return new r01(this, v61Var, ep1Var, null);
    }

    public final Context f() {
        return uy0.a(this.n2.b);
    }

    public final String g() {
        return r91.a(this.b).o.a == 3 ? "rewarded_interstitial" : "rewarded";
    }
}
