package defpackage;

/* loaded from: classes.dex */
public final class un {
    public static final in a;
    public static final in b;
    public static final in c;
    public static final in d;
    public static final in e;
    public static final in f;
    public static final in g;
    public static final in h;
    public static final in i;
    public static final in j;
    public static final in k;
    public static final in l;
    public static final in m;
    public static final in n;
    public static final in o;
    public static final in p;

    static {
        in inVar = new in();
        inVar.a = 3;
        inVar.b = "Google Play In-app Billing API version is less than 3";
        a = inVar;
        in inVar2 = new in();
        inVar2.a = 3;
        inVar2.b = "Google Play In-app Billing API version is less than 9";
        b = inVar2;
        in inVar3 = new in();
        inVar3.a = 3;
        inVar3.b = "Billing service unavailable on device.";
        c = inVar3;
        in inVar4 = new in();
        inVar4.a = 5;
        inVar4.b = "Client is already in the process of connecting to billing service.";
        d = inVar4;
        in inVar5 = new in();
        inVar5.a = 3;
        inVar5.b = "Play Store version installed does not support cross selling products.";
        in inVar6 = new in();
        inVar6.a = 5;
        inVar6.b = "The list of SKUs can't be empty.";
        e = inVar6;
        in inVar7 = new in();
        inVar7.a = 5;
        inVar7.b = "SKU type can't be empty.";
        f = inVar7;
        in inVar8 = new in();
        inVar8.a = -2;
        inVar8.b = "Client does not support extra params.";
        g = inVar8;
        in inVar9 = new in();
        inVar9.a = -2;
        inVar9.b = "Client does not support the feature.";
        h = inVar9;
        in inVar10 = new in();
        inVar10.a = -2;
        inVar10.b = "Client does not support get purchase history.";
        in inVar11 = new in();
        inVar11.a = 5;
        inVar11.b = "Invalid purchase token.";
        i = inVar11;
        in inVar12 = new in();
        inVar12.a = 6;
        inVar12.b = "An internal error occurred.";
        j = inVar12;
        in inVar13 = new in();
        inVar13.a = 4;
        inVar13.b = "Item is unavailable for purchase.";
        in inVar14 = new in();
        inVar14.a = 5;
        inVar14.b = "SKU can't be null.";
        in inVar15 = new in();
        inVar15.a = 5;
        inVar15.b = "SKU type can't be null.";
        in inVar16 = new in();
        inVar16.a = 0;
        inVar16.b = "";
        k = inVar16;
        in inVar17 = new in();
        inVar17.a = -1;
        inVar17.b = "Service connection is disconnected.";
        l = inVar17;
        in inVar18 = new in();
        inVar18.a = -3;
        inVar18.b = "Timeout communicating with service.";
        m = inVar18;
        in inVar19 = new in();
        inVar19.a = -2;
        inVar19.b = "Client doesn't support subscriptions.";
        n = inVar19;
        in inVar20 = new in();
        inVar20.a = -2;
        inVar20.b = "Client doesn't support subscriptions update.";
        o = inVar20;
        in inVar21 = new in();
        inVar21.a = -2;
        inVar21.b = "Client doesn't support multi-item purchases.";
        p = inVar21;
        in inVar22 = new in();
        inVar22.a = 5;
        inVar22.b = "Unknown feature";
    }
}
