package defpackage;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.text.TextUtils;
import com.google.android.gms.ads.internal.util.zzbr;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.apache.commons.lang3.time.DateUtils;

/* loaded from: classes.dex */
public final class y40 {
    public static final o40<Boolean> A;
    public static final o40<Boolean> A0;
    public static final o40<Boolean> A1;
    public static final o40<Boolean> A2;
    public static final o40<Long> A3;
    public static final o40<Integer> A4;
    public static final o40<Boolean> B;
    public static final o40<Long> B0;
    public static final o40<Boolean> B1;
    public static final o40<Boolean> B2;
    public static final o40<Integer> B3;
    public static final o40<Integer> B4;
    public static final o40<String> C;
    public static final o40<Long> C0;
    public static final o40<Boolean> C1;
    public static final o40<Long> C2;
    public static final o40<Integer> C3;
    public static final o40<Boolean> C4;
    public static final o40<Integer> D;
    public static final o40<Boolean> D0;
    public static final o40<Boolean> D1;
    public static final o40<String> D2;
    public static final o40<Integer> D3;
    public static final o40<Boolean> D4;
    public static final o40<Boolean> E;
    public static final o40<Long> E0;
    public static final o40<String> E1;
    public static final o40<String> E2;
    public static final o40<Integer> E3;
    public static final o40<String> E4;
    public static final o40<String> F;
    public static final o40<Boolean> F0;
    public static final o40<Boolean> F1;
    public static final o40<String> F2;
    public static final o40<Boolean> F3;
    public static final o40<Integer> F4;
    public static final o40<String> G;
    public static final o40<Long> G0;
    public static final o40<Boolean> G1;
    public static final o40<String> G2;
    public static final o40<Boolean> G3;
    public static final o40<Boolean> G4;
    public static final o40<String> H;
    public static final o40<Boolean> H0;
    public static final o40<Boolean> H1;
    public static final o40<Integer> H2;
    public static final o40<Boolean> H3;
    public static final o40<Integer> H4;
    public static final o40<String> I;
    public static final o40<Boolean> I0;
    public static final o40<Boolean> I1;
    public static final o40<Integer> I2;
    public static final o40<String> I3;
    public static final o40<Integer> I4;
    public static final o40<Boolean> J;
    public static final o40<Boolean> J0;
    public static final o40<Boolean> J1;
    public static final o40<Boolean> J2;
    public static final o40<Boolean> J3;
    public static final o40<Boolean> J4;
    public static final o40<Boolean> K;
    public static final o40<Boolean> K0;
    public static final o40<Boolean> K1;
    public static final o40<Boolean> K2;
    public static final o40<Integer> K3;
    public static final o40<Boolean> K4;
    public static final o40<Integer> L;
    public static final o40<Boolean> L0;
    public static final o40<Boolean> L1;
    public static final o40<Boolean> L2;
    public static final o40<Boolean> L3;
    public static final o40<Boolean> L4;
    public static final o40<Integer> M;
    public static final o40<String> M0;
    public static final o40<Boolean> M1;
    public static final o40<Integer> M2;
    public static final o40<Boolean> M3;
    public static final o40<Boolean> M4;
    public static final o40<Integer> N;
    public static final o40<String> N0;
    public static final o40<Boolean> N1;
    public static final o40<Boolean> N2;
    public static final o40<Integer> N3;
    public static final o40<Boolean> N4;
    public static final o40<String> O;
    public static final o40<Boolean> O0;
    public static final o40<Boolean> O1;
    public static final o40<Boolean> O2;
    public static final o40<Boolean> O3;
    public static final o40<String> O4;
    public static final o40<String> P;
    public static final o40<Long> P0;
    public static final o40<Boolean> P1;
    public static final o40<Boolean> P2;
    public static final o40<Boolean> P3;
    public static final o40<Boolean> P4;
    public static final o40<Boolean> Q;
    public static final o40<Long> Q0;
    public static final o40<String> Q1;
    public static final o40<String> Q2;
    public static final o40<Boolean> Q3;
    public static final o40<Boolean> Q4;
    public static final o40<Boolean> R;
    public static final o40<Boolean> R0;
    public static final o40<String> R1;
    public static final o40<String> R2;
    public static final o40<Boolean> R3;
    public static final o40<Integer> R4;
    public static final o40<Boolean> S;
    public static final o40<Boolean> S0;
    public static final o40<String> S1;
    public static final o40<Integer> S2;
    public static final o40<Integer> S3;
    public static final o40<Boolean> S4;
    public static final o40<Boolean> T;
    public static final o40<Boolean> T0;
    public static final o40<Boolean> T1;
    public static final o40<Boolean> T2;
    public static final o40<Integer> T3;
    public static final o40<Boolean> T4;
    public static final o40<String> U;
    public static final o40<String> U0;
    public static final o40<Integer> U1;
    public static final o40<Integer> U2;
    public static final o40<String> U3;
    public static final o40<Boolean> U4;
    public static final o40<String> V;
    public static final o40<Long> V0;
    public static final o40<Boolean> V1;
    public static final o40<Boolean> V2;
    public static final o40<String> V3;
    public static final o40<Integer> V4;
    public static final o40<Boolean> W;
    public static final o40<Boolean> W0;
    public static final o40<Boolean> W1;
    public static final o40<Boolean> W2;
    public static final o40<String> W3;
    public static final o40<Integer> W4;
    public static final o40<String> X;
    public static final o40<Boolean> X0;
    public static final o40<Boolean> X1;
    public static final o40<Boolean> X2;
    public static final o40<String> X3;
    public static final o40<Boolean> X4;
    public static final o40<Long> Y;
    public static final o40<Boolean> Y0;
    public static final o40<String> Y1;
    public static final o40<Integer> Y2;
    public static final o40<Integer> Y3;
    public static final o40<Boolean> Y4;
    public static final o40<Integer> Z;
    public static final o40<String> Z0;
    public static final o40<Boolean> Z1;
    public static final o40<Integer> Z2;
    public static final o40<Integer> Z3;
    public static final o40<Boolean> Z4;
    public static final o40<String> a = new r40("gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final o40<Boolean> a0;
    public static final o40<Boolean> a1;
    public static final o40<Boolean> a2;
    public static final o40<Boolean> a3;
    public static final o40<Integer> a4;
    public static final o40<Boolean> a5;
    public static final o40<String> b;
    public static final o40<Integer> b0;
    public static final o40<Boolean> b1;
    public static final o40<Boolean> b2;
    public static final o40<String> b3;
    public static final o40<Integer> b4;
    public static final o40<Boolean> b5;
    public static final o40<Integer> c;
    public static final o40<Boolean> c0;
    public static final o40<Boolean> c1;
    public static final o40<Boolean> c2;
    public static final o40<Boolean> c3;
    public static final o40<String> c4;
    public static final o40<Boolean> c5;
    public static final o40<Integer> d;
    public static final o40<Boolean> d0;
    public static final o40<Boolean> d1;
    public static final o40<Boolean> d2;
    public static final o40<Boolean> d3;
    public static final o40<String> d4;
    public static final o40<Boolean> d5;
    public static final o40<Integer> e;
    public static final o40<Boolean> e0;
    public static final o40<Integer> e1;
    public static final o40<Boolean> e2;
    public static final o40<Boolean> e3;
    public static final o40<String> e4;
    public static final o40<Boolean> e5;
    public static final o40<Integer> f;
    public static final o40<Boolean> f0;
    public static final o40<Boolean> f1;
    public static final o40<Boolean> f2;
    public static final o40<Boolean> f3;
    public static final o40<String> f4;
    public static final o40<Boolean> f5;
    public static final o40<Integer> g;
    public static final o40<Boolean> g0;
    public static final o40<Boolean> g1;
    public static final o40<Boolean> g2;
    public static final o40<Boolean> g3;
    public static final o40<Integer> g4;
    public static final o40<Integer> g5;
    public static final o40<Integer> h;
    public static final o40<Boolean> h0;
    public static final o40<Boolean> h1;
    public static final o40<Long> h2;
    public static final o40<Integer> h3;
    public static final o40<String> h4;
    public static final o40<Integer> h5;
    public static final o40<String> i;
    public static final o40<Boolean> i0;
    public static final o40<Integer> i1;
    public static final o40<Long> i2;
    public static final o40<Boolean> i3;
    public static final o40<Integer> i4;
    public static final o40<Integer> i5;
    public static final o40<Integer> j;
    public static final o40<Boolean> j0;
    public static final o40<Long> j1;
    public static final o40<Boolean> j2;
    public static final o40<Boolean> j3;
    public static final o40<Integer> j4;
    public static final o40<Boolean> j5;
    public static final o40<Boolean> k;
    public static final o40<String> k0;
    public static final o40<Long> k1;
    public static final o40<Boolean> k2;
    public static final o40<Boolean> k3;
    public static final o40<Boolean> k4;
    public static final o40<Boolean> k5;
    public static final o40<Boolean> l;
    public static final o40<Boolean> l0;
    public static final o40<Boolean> l1;
    public static final o40<Boolean> l2;
    public static final o40<Boolean> l3;
    public static final o40<Boolean> l4;
    public static final o40<Boolean> m;
    public static final o40<Boolean> m0;
    public static final o40<Boolean> m1;
    public static final o40<Long> m2;
    public static final o40<String> m3;
    public static final o40<Boolean> m4;
    public static final o40<Integer> n;
    public static final o40<String> n0;
    public static final o40<Boolean> n1;
    public static final o40<Boolean> n2;
    public static final o40<Integer> n3;
    public static final o40<Boolean> n4;
    public static final o40<Integer> o;
    public static final o40<Boolean> o0;
    public static final o40<Boolean> o1;
    public static final o40<Boolean> o2;
    public static final o40<Boolean> o3;
    public static final o40<Boolean> o4;
    public static final o40<Integer> p;
    public static final o40<Boolean> p0;
    public static final o40<Boolean> p1;
    public static final o40<Long> p2;
    public static final o40<Boolean> p3;
    public static final o40<String> p4;
    public static final o40<Long> q;
    public static final o40<Boolean> q0;
    public static final o40<Boolean> q1;
    public static final o40<Long> q2;
    public static final o40<Boolean> q3;
    public static final o40<Boolean> q4;
    public static final o40<Long> r;
    public static final o40<Integer> r0;
    public static final o40<Boolean> r1;
    public static final o40<Boolean> r2;
    public static final o40<Boolean> r3;
    public static final o40<Boolean> r4;
    public static final o40<Integer> s;
    public static final o40<Boolean> s0;
    public static final o40<Boolean> s1;
    public static final o40<Boolean> s2;
    public static final o40<Boolean> s3;
    public static final o40<Boolean> s4;
    public static final o40<String> t;
    public static final o40<Boolean> t0;
    public static final o40<Boolean> t1;
    public static final o40<Boolean> t2;
    public static final o40<Boolean> t3;
    public static final o40<Boolean> t4;
    public static final o40<Long> u;
    public static final o40<Boolean> u0;
    public static final o40<Boolean> u1;
    public static final o40<String> u2;
    public static final o40<Boolean> u3;
    public static final o40<Integer> u4;
    public static final o40<Boolean> v;
    public static final o40<Boolean> v0;
    public static final e60<Boolean> v1;
    public static final o40<Integer> v2;
    public static final o40<Boolean> v3;
    public static final o40<Integer> v4;
    public static final o40<Long> w;
    public static final o40<Boolean> w0;
    public static final o40<Boolean> w1;
    public static final o40<Boolean> w2;
    public static final o40<Boolean> w3;
    public static final o40<Boolean> w4;
    public static final o40<Boolean> x;
    public static final o40<String> x0;
    public static final o40<Long> x1;
    public static final o40<Boolean> x2;
    public static final o40<Boolean> x3;
    public static final o40<Boolean> x4;
    public static final o40<Integer> y;
    public static final o40<Boolean> y0;
    public static final o40<Boolean> y1;
    public static final o40<Boolean> y2;
    public static final o40<Boolean> y3;
    public static final o40<Boolean> y4;
    public static final o40<Long> z;
    public static final o40<Boolean> z0;
    public static final o40<Boolean> z1;
    public static final o40<Boolean> z2;
    public static final o40<Boolean> z3;
    public static final o40<Boolean> z4;

    static {
        new r40("gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
        e60<Boolean> e60Var = s60.c;
        o40.b("gads:http_url_connection_factory:timeout_millis", 10000);
        b = new r40("gads:video_exo_player:version", "3");
        c = o40.b("gads:video_exo_player:connect_timeout", 8000);
        d = o40.b("gads:video_exo_player:read_timeout", 8000);
        e = o40.b("gads:video_exo_player:loading_check_interval", 1048576);
        f = o40.b("gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
        g = o40.b("gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
        h = o40.b("gads:video_exo_player_socket_receive_buffer_size", 0);
        i = new r40("gads:video_exo_player:precache_exceptions", "");
        j = o40.b("gads:video_exo_player:min_retry_count", -1);
        Boolean bool = Boolean.TRUE;
        k = new n40(1, "gads:video_exo_player:fmp4_extractor_enabled", bool);
        Boolean bool2 = Boolean.FALSE;
        l = new n40(1, "gads:video_exo_player:use_play_back_info_for_should_start_play_back", bool2);
        m = new n40(1, "gads:video_exo_player:treat_load_exception_as_non_fatal", bool2);
        n = o40.b("gads:video_stream_cache:limit_count", 5);
        o = o40.b("gads:video_stream_cache:limit_space", 8388608);
        p = o40.b("gads:video_stream_exo_cache:buffer_size", 8388608);
        q = o40.h("gads:video_stream_cache:limit_time_sec", 300L);
        r = o40.h("gads:video_stream_cache:notify_interval_millis", 125L);
        s = o40.b("gads:video_stream_cache:connect_timeout_millis", 10000);
        t = new r40("gads:video:metric_frame_hash_times", "");
        u = o40.h("gads:video:metric_frame_hash_time_leniency", 500L);
        v = new n40(1, "gads:video:force_watermark", bool2);
        w = o40.h("gads:video:surface_update_min_spacing_ms", 1000L);
        x = new n40(1, "gads:video:spinner:enabled", bool2);
        y = o40.b("gads:video:spinner:scale", 4);
        z = o40.h("gads:video:spinner:jank_threshold_ms", 50L);
        A = new n40(1, "gads:video:aggressive_media_codec_release", bool2);
        B = new n40(1, "gads:memory_bundle:debug_info", bool2);
        C = new r40("gads:video:codec_query_mime_types", "");
        D = o40.b("gads:video:codec_query_minimum_version", 16);
        E = new n40(1, "gads:video:set_black_background", bool2);
        F = new r40("gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
        G = new r40("gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
        H = new r40("gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
        I = new r40("gad:mraid:version", "3.0");
        J = new n40(1, "gads:mraid:expanded_interstitial_fix", bool2);
        K = new n40(1, "gads:mraid:initial_size_fallback", bool2);
        L = o40.b("gads:content_vertical_fingerprint_number", 100);
        M = o40.b("gads:content_vertical_fingerprint_bits", 23);
        N = o40.b("gads:content_vertical_fingerprint_ngram", 3);
        O = new r40("gads:content_fetch_view_tag_id", "googlebot");
        P = new r40("gads:content_fetch_exclude_view_tag", "none");
        Q = new n40(1, "gads:content_fetch_disable_get_title_from_webview", bool2);
        R = new n40(1, "gads:content_fetch_enable_new_content_score", bool2);
        S = new n40(1, "gads:content_fetch_enable_serve_once", bool2);
        T = new n40(1, "gads:sai:enabled", bool);
        U = new r40("gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
        V = new r40("gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
        W = new n40(1, "gads:sai:using_macro:enabled", bool2);
        X = new r40("gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
        Y = o40.h("gads:sai:timeout_ms", -1L);
        Z = o40.b("gads:sai:scion_thread_pool_size", 5);
        a0 = new n40(1, "gads:sai:app_measurement_enabled3", bool2);
        b0 = o40.b("gads:sai:app_measurement_min_client_dynamite_version", 20290);
        c0 = new n40(1, "gads:sai:force_through_reflection", bool);
        d0 = new n40(1, "gads:sai:gmscore_availability_check_disabled", bool2);
        e0 = new n40(1, "gads:sai:logging_disabled_for_drx", bool2);
        f0 = new n40(1, "gads:sai:app_measurement_npa_enabled", bool2);
        g0 = new n40(1, "gads:idless:idless_disables_attestation", bool);
        Boolean bool3 = Boolean.TRUE;
        h0 = new n40(1, "gads:idless:app_measurement_idless_enabled", bool3);
        Boolean bool4 = Boolean.FALSE;
        i0 = new n40(1, "gads:sai:server_side_npa:disable_writing", bool4);
        j0 = new n40(1, "gads:sai:server_side_npa:enabled", bool4);
        k0 = new r40("gads:sai:server_side_npa:shared_preference_key_list", "{  \"__default__\": [    \"IABTCF_TCString\"  ],  \"mobileads_consent\": [    \"consent_string\"  ]}");
        l0 = new n40(1, "gads:idless:internal_state_enabled", bool3);
        m0 = new n40(1, "gads:idless:idless_disables_offline_ads_signalling", bool3);
        n0 = new r40("gads:idless:cookie_modification", "=; Max-Age=-1; path=/; domain=.doubleclick.net");
        o0 = new n40(1, "gads:interstitial:app_must_be_foreground:enabled", bool4);
        p0 = new n40(1, "gads:interstitial:foreground_report:enabled", bool4);
        q0 = new n40(1, "gads:interstitial:default_immersive", bool4);
        r0 = o40.b("gads:show_interstitial_with_context:min_version", 999999999);
        s0 = new n40(1, "gads:webview:error_web_response:enabled", bool4);
        t0 = new n40(1, "gads:webview:pause_interstitial:enabled", bool3);
        new n40(1, "gads:rsku:webviewgone:kill_process:enabled", bool4);
        u0 = new n40(1, "gads:webviewgone:kill_process:enabled", bool4);
        new n40(1, "gads:rsku:webviewgone:new_onshow:enabled", bool3);
        v0 = new n40(1, "gads:webviewgone:new_onshow:enabled", bool4);
        w0 = new n40(1, "gads:webview:pause_resume:enabled", bool3);
        x0 = new r40("gads:webview_cookie_url", "googleads.g.doubleclick.net");
        new n40(1, "gads:new_rewarded_ad:enabled", bool3);
        y0 = new n40(1, "gads:rewarded:adapter_initialization_enabled", bool4);
        o40.h("gads:rewarded:adapter_timeout_ms", 20000L);
        z0 = new n40(1, "gads:rewarded:ad_metadata_enabled", bool4);
        A0 = new n40(1, "gads:rewarded:ssv_custom_data_enabled", bool3);
        B0 = o40.h("gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
        C0 = o40.h("gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
        D0 = new n40(1, "gads:adid_values_in_adrequest:enabled", bool4);
        E0 = o40.h("gads:adid_values_in_adrequest:timeout", 2000L);
        F0 = new n40(1, "gads:disable_adid_values_in_ms", bool4);
        G0 = o40.h("gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
        H0 = new n40(1, "gads:custom_close_blocking:enabled", bool4);
        I0 = new n40(1, "gads:disabling_closable_area:enabled", bool4);
        J0 = new n40(1, "gads:use_system_ui_for_fullscreen:enabled", bool4);
        K0 = new n40(1, "gads:ad_overlay:collect_cutout_info:enabled", bool4);
        new n40(1, "gads:impression_optimization_enabled", bool4);
        new r40("gads:banner_ad_pool:schema", "customTargeting");
        o40.b("gads:banner_ad_pool:max_queues", 3);
        o40.b("gads:banner_ad_pool:max_pools", 3);
        L0 = new n40(1, "gads:delay_banner_renderer:enabled", bool3);
        new n40(1, "gads:interstitial_ad_pool:enabled", bool4);
        new n40(1, "gads:interstitial_ad_pool:enabled_for_rewarded", bool4);
        new r40("gads:interstitial_ad_pool:schema", "customTargeting");
        new r40("gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        o40.b("gads:interstitial_ad_pool:max_pools", 3);
        o40.b("gads:interstitial_ad_pool:max_pool_depth", 2);
        o40.b("gads:interstitial_ad_pool:time_limit_sec", 1200);
        new r40("gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        o40.b("gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
        o40.b("gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
        o40.h("gads:interstitial_ad_pool:discard_thresholds", 0L);
        o40.h("gads:interstitial_ad_pool:miss_thresholds", 0L);
        new s40("gads:interstitial_ad_pool:discard_asymptote", Float.valueOf(0.0f));
        new s40("gads:interstitial_ad_pool:miss_asymptote", Float.valueOf(0.0f));
        M0 = new r40("gads:spherical_video:vertex_shader", "");
        N0 = new r40("gads:spherical_video:fragment_shader", "");
        O0 = new n40(1, "gads:include_local_global_rectangles", bool4);
        P0 = o40.h("gads:position_watcher:throttle_ms", 200L);
        Q0 = o40.h("gads:position_watcher:scroll_aware_throttle_ms", 33L);
        R0 = new n40(1, "gads:position_watcher:enable_scroll_aware_ads", bool4);
        S0 = new n40(1, "gads:position_watcher:send_scroll_data", bool4);
        new n40(1, "gads:gen204_signals:enabled", bool4);
        T0 = new n40(1, "gads:extra_sdk_versions_for_crash_reports:enabled", bool3);
        U0 = new r40("gads:logged_adapter_version_classes", "");
        V0 = o40.h("gads:rtb_v1_1:signal_timeout_ms", 1000L);
        W0 = new n40(1, "gads:rtb_signal:enabled", bool3);
        X0 = new n40(1, "gads:rtb_v1_1:cld:enabled", bool3);
        Y0 = new n40(1, "gads:rtb_v1_1:cld:check_regex:enabled", bool3);
        Z0 = new r40("gads:rtb_logging:regex", "(?!)");
        a1 = new n40(1, "gads:presentation_error:urls_enabled", bool3);
        b1 = new n40(1, "gads:rtb_interstitial:use_fullscreen_monitor", bool3);
        c1 = new n40(1, "gads:native_required_assets:enabled", bool4);
        Boolean bool5 = Boolean.TRUE;
        d1 = new n40(1, "gads:native_required_assets:check_inner_mediaview:enabled", bool5);
        e1 = o40.b("gads:native_ad_options_rtb:min_version", 999999999);
        Boolean bool6 = Boolean.FALSE;
        f1 = new n40(1, "gads:track_view_next_runloop:enabled", bool6);
        g1 = new n40(1, "gads:native_required_assets:viewability:enabled", bool6);
        h1 = new n40(1, "gads:v1_1:adapter_initialization:enabled", bool5);
        i1 = o40.b("gads:adapter_initialization:min_sdk_version", 15301000);
        j1 = o40.h("gads:adapter_initialization:timeout", 30L);
        k1 = o40.h("gads:adapter_initialization:cld_timeout", 10L);
        l1 = new n40(1, "gads:additional_video_csi:enabled", bool6);
        m1 = new n40(1, "gads:csi:enabled_per_sampling", bool6);
        n1 = new n40(1, "gads:always_set_transfer_listener:enabled", bool6);
        o1 = new n40(1, "gads:initialization_csi:enabled", bool6);
        new n40(1, "gads:initialization_csi_control:enabled", bool6);
        p1 = new n40(1, "gads:msa:experiments:enabled", bool6);
        q1 = new n40(1, "gads:msa:experiments:ps:enabled", bool6);
        r1 = new n40(1, "gads:msa:experiments:fb:enabled", bool5);
        s1 = new n40(1, "gads:msa:experiments:ps:er", bool5);
        o40.b("gads:gestures:a2:enabled", 0);
        t1 = new n40(1, "gads:msa:experiments:a2", bool6);
        u1 = new n40(1, "gads:gestures:clearTd:enabled", bool6);
        v1 = t60.b;
        w1 = new n40(1, "gads:gestures:errorlogging:enabled", bool6);
        x1 = o40.h("gads:gestures:task_timeout", 2000L);
        y1 = new n40(1, "gads:gestures:asig:enabled", bool6);
        z1 = new n40(1, "gads:gestures:ans:enabled", bool6);
        A1 = new n40(1, "gads:gestures:tos:enabled", bool6);
        new n40(1, "gads:gestures:brt:enabled", bool5);
        B1 = new n40(1, "gads:gestures:fpi:enabled", bool6);
        C1 = new n40(1, "gads:signal:app_permissions:disabled", bool6);
        D1 = new n40(1, "gads:gestures:hpk:enabled", bool5);
        E1 = new r40("gads:gestures:pk", "");
        F1 = new n40(1, "gads:gestures:bs:enabled", bool5);
        G1 = new n40(1, "gads:gestures:check_initialization_thread:enabled", bool6);
        H1 = new n40(1, "gads:gestures:init_new_thread:enabled", bool5);
        I1 = new n40(1, "gads:gestures:pds:enabled", bool5);
        o40.b("gads:gestures:as2percentage", 0);
        J1 = new n40(1, "gads:gestures:ns:enabled", bool5);
        K1 = new n40(1, "gads:gestures:vdd:enabled", bool6);
        L1 = new n40(1, "gads:native:asset_view_touch_events", bool6);
        M1 = new n40(1, "gads:native:set_touch_listener_on_asset_views", bool5);
        N1 = new n40(1, "gads:ais:enabled", bool5);
        O1 = new n40(1, "gads:stav:enabled", bool6);
        P1 = new n40(1, "gads:send_available_disk_space:enabled", bool6);
        os3.j.d.b.add(new r40("gads:sdk_core_constants:experiment_id", null));
        Q1 = new r40("gads:sdk_core_constants:caps", "");
        new n40(1, "gads:js_flags:disable_phenotype", bool6);
        R1 = new r40("gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        new r40("gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
        S1 = new r40("gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
        T1 = new n40(1, "gads:native:get_native_ad_view_signals", bool6);
        U1 = o40.b("gads:native_video_load_timeout", 10);
        o40.b("gads:omid:native_webview_load_timeout", 2000);
        V1 = new n40(1, "gads:omid:native_video_ad_user_action_event:enabled", bool6);
        W1 = new n40(1, "gads:enable_native_media_aspect_ratio", bool5);
        X1 = o40.a(1, "gads:native:media_content_main_image:enabled", bool5);
        Y1 = o40.c("gads:ad_choices_content_description", "Ad Choices Icon");
        o40.a(1, "gads:enable_store_active_view_state", bool6);
        Z1 = o40.a(1, "gads:enable_singleton_broadcast_receiver", bool6);
        a2 = o40.a(1, "gads:native:media_view_match_parent:enabled", bool6);
        b2 = o40.a(1, "gads:native:count_impression_for_assets", bool6);
        Boolean bool7 = Boolean.TRUE;
        o40.a(1, "gads:instream_ad:enabled", bool7);
        Boolean bool8 = Boolean.FALSE;
        c2 = o40.a(1, "gads:fluid_ad:use_wrap_content_height", bool8);
        o40.a(1, "gads:auto_location_for_coarse_permission", bool8);
        o40.g("gads:auto_location_for_coarse_permission:experiment_id");
        o40.h("gads:auto_location_timeout", 2000L);
        o40.g("gads:auto_location_timeout:experiment_id");
        o40.h("gads:auto_location_interval", -1L);
        o40.g("gads:auto_location_interval:experiment_id");
        d2 = o40.a(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", bool7);
        e2 = o40.a(1, "gads:get_request_signals_cld:enabled", bool7);
        f2 = o40.a(1, "gads:get_request_signals_common_cld:enabled", bool8);
        g2 = o40.a(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", bool7);
        h2 = o40.h("gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
        i2 = o40.h("gads:parental_controls:timeout", 2000L);
        o40.b("gads:cache:ad_request_timeout_millis", 250);
        o40.b("gads:cache:max_concurrent_downloads", 10);
        o40.a(1, "gads:cache:downloader_use_high_priority", bool8);
        o40.h("gads:cache:javascript_timeout_millis", 5000L);
        j2 = o40.a(1, "gads:cache:bind_on_foreground", bool8);
        k2 = o40.a(1, "gads:cache:bind_on_init", bool8);
        l2 = o40.a(1, "gads:cache:bind_on_request", bool8);
        m2 = o40.h("gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
        n2 = o40.a(1, "gads:cache:use_cache_data_source", bool8);
        o2 = o40.a(1, "gads:cache:connection_per_read", bool8);
        p2 = o40.h("gads:cache:connection_timeout", 5000L);
        q2 = o40.h("gads:cache:read_only_connection_timeout", 5000L);
        r2 = o40.a(1, "gads:cache:read_inner_data_source_if_gcache_miss", bool8);
        s2 = o40.a(1, "gads:cache:read_inner_data_source_if_gcache_not_downloaded", bool8);
        o40.a(1, "gads:cache:function_call_timeout_v1:enabled", bool8);
        o40.h("gads:cache:function_call_timeout", 5000L);
        t2 = o40.a(1, "gads:http_assets_cache:enabled", bool8);
        u2 = o40.c("gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
        v2 = o40.b("gads:http_assets_cache:time_out", 100);
        w2 = o40.a(1, "gads:chrome_custom_tabs_browser:enabled", bool8);
        x2 = o40.a(1, "gads:chrome_custom_tabs:disabled", bool8);
        y2 = o40.a(1, "gads:chrome_custom_tabs_browser_v2:enabled", bool8);
        z2 = o40.a(1, "gads:cct_v2_connection:enabled", bool8);
        A2 = o40.a(1, "gads:cct_v2_direct_launch:enabled", bool8);
        B2 = o40.a(1, "gads:chrome_custom_tabs_for_native_ads:enabled", bool8);
        C2 = o40.h("gads:debug_hold_gesture:time_millis", 2000L);
        D2 = o40.c("gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        E2 = o40.c("gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        F2 = o40.c("gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        G2 = o40.c("gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        H2 = o40.b("gads:drx_debug:timeout_ms", 5000);
        I2 = o40.b("gad:pixel_dp_comparision_multiplier", 1);
        J2 = o40.a(1, "gad:interstitial_for_multi_window", bool8);
        K2 = o40.a(1, "gad:interstitial_ad_stay_active_in_multi_window", bool8);
        L2 = o40.a(1, "gad:interstitial_multi_window_method", bool8);
        M2 = o40.b("gad:interstitial:close_button_padding_dip", 0);
        N2 = o40.a(1, "gads:clearcut_logging:enabled", bool8);
        O2 = o40.a(1, "gads:clearcut_logging:write_to_file", bool8);
        P2 = o40.a(1, "gad:publisher_testing:force_local_request:enabled", bool7);
        Q2 = o40.c("gad:publisher_testing:force_local_request:enabled_list", "");
        R2 = o40.c("gad:publisher_testing:force_local_request:disabled_list", "");
        S2 = o40.b("gad:http_redirect_max_count:times", 8);
        T2 = o40.a(1, "gads:omid:enabled", bool7);
        U2 = o40.b("gads:omid:destroy_webview_delay", 1000);
        o40.a(1, "gads:omid_1_3_activate:enabled", bool8);
        V2 = o40.a(1, "gads:omid_1_3_create_html_session:enabled", bool8);
        W2 = o40.a(1, "gads:omid_1_3_create_js_session:enabled", bool8);
        o40.a(1, "gads:omid_1_3_friendly_obstruction:enabled", bool8);
        X2 = o40.a(1, "gads:omid_1_3_fire_loaded_event:enabled", bool8);
        Boolean bool9 = Boolean.TRUE;
        o40.a(1, "gads:nonagon:banner:enabled", bool9);
        o40.c("gads:nonagon:banner:ad_unit_exclusions", "(?!)");
        o40.a(1, "gads:nonagon:app_open:enabled", bool9);
        Y2 = o40.b("gads:app_open_beta:min_version", 999999999);
        Z2 = o40.b("gads:app_open_ad_open_beta_api:min_version", 202490999);
        o40.c("gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
        o40.a(1, "gads:nonagon:interstitial:enabled", bool9);
        o40.c("gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
        o40.a(1, "gads:nonagon:rewardedvideo:enabled", bool9);
        a3 = o40.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", bool9);
        b3 = o40.c("gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
        o40.a(1, "gads:nonagon:nativead:enabled", bool9);
        o40.c("gads:nonagon:nativead:app_name", "(?!)");
        c3 = o40.a(1, "gads:nonagon:banner:check_dp_size", bool9);
        d3 = o40.a(1, "gads:nonagon:rewarded:load_multiple_ads", bool9);
        Boolean bool10 = Boolean.FALSE;
        o40.a(1, "gads:nonagon:return_last_error_code", bool10);
        e3 = o40.a(1, "gads:nonagon:return_no_fill_error_code", bool10);
        f3 = o40.a(1, "gads:nonagon:continue_on_no_fill", bool10);
        o40.a(1, "gads:nonagon:open_not_loaded_interstitial", bool9);
        g3 = o40.a(1, "gads:nonagon:separate_timeout:enabled", bool9);
        h3 = o40.b("gads:nonagon:request_timeout:seconds", 60);
        i3 = o40.a(1, "gads:nonagon:banner_recursive_renderer", bool10);
        j3 = o40.a(1, "gads:nonagon:app_stats_lock:enabled", bool10);
        k3 = o40.a(1, "gads:nonagon:app_stats_main_thread:enabled", bool10);
        l3 = o40.a(1, "gads:uri_query_to_map_bg_thread:enabled", bool10);
        m3 = o40.c("gads:uri_query_to_map_bg_thread:types", "/result");
        n3 = o40.b("gads:uri_query_to_map_bg_thread:min_length", 1000);
        o3 = o40.a(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", bool9);
        p3 = o40.a(1, "gads:active_view_gmsg_separate_pool:enabled", bool9);
        o40.a(1, "gads:nonagon:service:enabled", bool9);
        q3 = o40.a(1, "gads:signals:ad_id_info:enabled", bool10);
        r3 = o40.a(1, "gads:signals:app_index:enabled", bool10);
        s3 = o40.a(1, "gads:signals:attestation_token:enabled", bool10);
        t3 = o40.a(1, "gads:signals:cache:enabled", bool10);
        o40.a(1, "gads:signals:doritos:enabled", bool10);
        u3 = o40.a(1, "gads:signals:doritos:v1:enabled", bool10);
        o40.a(1, "gads:signals:doritos:v2:immediate:enabled", bool10);
        o40.a(1, "gads:signals:network_prediction:enabled", bool10);
        v3 = o40.a(1, "gads:signals:parental_control:enabled", bool10);
        w3 = o40.a(1, "gads:signals:video_decoder:enabled", bool10);
        x3 = o40.a(1, "gads:signals:app_version_name:enabled", bool10);
        y3 = o40.a(1, "gads:signals:banner_hardware_acceleration:enabled", bool10);
        z3 = o40.a(1, "gads:signals:native_hardware_acceleration:enabled", bool10);
        o40.a(1, "gads:attestation_token:enabled", bool10);
        A3 = o40.h("gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", DateUtils.MILLIS_PER_HOUR);
        B3 = o40.b("gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
        C3 = o40.b("gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
        D3 = o40.b("gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
        E3 = o40.b("gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
        e60<Boolean> e60Var2 = u60.a;
        F3 = o40.a(1, "gads:consent:shared_preference_reading:enabled", bool9);
        G3 = o40.a(1, "gads:consent:iab_consent_info:enabled", bool9);
        H3 = o40.a(1, "gads:fc_consent:shared_preference_reading:enabled", bool9);
        I3 = o40.c("gads:sp:json_string", "");
        J3 = o40.a(1, "gads:nativeads:image:sample:enabled", bool9);
        K3 = o40.b("gads:nativeads:image:sample:pixels", 1048576);
        L3 = o40.a(1, "gads:nativeads:pub_image_scale_type:enabled", bool9);
        M3 = o40.a(1, "gads:offline_signaling:enabled", bool10);
        N3 = o40.b("gads:offline_signaling:log_maximum", 100);
        O3 = o40.a(1, "gads:nativeads:template_signal:enabled", bool9);
        P3 = o40.a(1, "gads:nativeads:media_content_aspect_ratio:enabled", bool9);
        Q3 = o40.a(1, "gads:nativeads:media_content_metadata:enabled", bool9);
        R3 = o40.a(1, "gads:precache_pool:verbose_logging", bool10);
        S3 = o40.b("gads:rewarded_precache_pool:count", 0);
        T3 = o40.b("gads:interstitial_precache_pool:count", 0);
        U3 = o40.c("gads:rewarded_precache_pool:discard_strategy", "lru");
        V3 = o40.c("gads:interstitial_precache_pool:discard_strategy", "lru");
        W3 = o40.c("gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
        X3 = o40.c("gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
        Y3 = o40.b("gads:rewarded_precache_pool:size", 1);
        Z3 = o40.b("gads:interstitial_precache_pool:size", 1);
        a4 = o40.b("gads:rewarded_precache_pool:ad_time_limit", 1200);
        b4 = o40.b("gads:interstitial_precache_pool:ad_time_limit", 1200);
        c4 = o40.c("gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        d4 = o40.c("gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        e4 = o40.c("gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        f4 = o40.c("gads:app_open_precache_pool:discard_strategy", "oldest");
        g4 = o40.b("gads:app_open_precache_pool:count", 0);
        h4 = o40.c("gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
        i4 = o40.b("gads:app_open_precache_pool:size", 1);
        j4 = o40.b("gads:app_open_precache_pool:ad_time_limit", 14400);
        Boolean bool11 = Boolean.FALSE;
        k4 = o40.a(1, "gads:memory_leak:b129558083", bool11);
        l4 = o40.a(1, "gads:unhandled_event_reporting:enabled", bool11);
        Boolean bool12 = Boolean.TRUE;
        m4 = o40.a(1, "gads:response_info:enabled", bool12);
        n4 = o40.a(1, "gads:csi:interstitial_failed_to_show:enabled", bool11);
        o4 = o40.a(1, "gads:csi:mediation_failure:enabled", bool11);
        p4 = o40.c("gads:csi:error_parsing:regex", "^(\\d+)");
        q4 = o40.a(1, "gads:csi:eids_from_cld:enabled", bool11);
        r4 = o40.a(1, "gads:request_id_check:enabled", bool11);
        s4 = o40.a(1, "gads:request_id_int32:enabled", bool12);
        t4 = o40.a(1, "gads:signal_collection_without_rendering:enabled", bool12);
        u4 = o40.b("gads:native_ads_signal:timeout", 1000);
        v4 = o40.b("gads:signal_v2:min_version", 19677000);
        w4 = o40.a(2, "DISABLE_CRASH_REPORTING", bool11);
        x4 = o40.a(1, "gads:paid_event_listener:enabled", bool11);
        y4 = o40.a(1, "gads:interscroller_ad:enabled", bool12);
        z4 = o40.a(1, "gads:interscroller_ad:refresh:enabled", bool11);
        A4 = o40.b("gads:interscroller:min_width", 300);
        B4 = o40.b("gads:interscroller:min_height", 250);
        C4 = o40.a(1, "gads:is_in_scroll_view_new_api:enabled", bool12);
        D4 = o40.a(1, "gads:policy_validator_for_all_pubs:enabled", bool11);
        E4 = o40.c("gad:publisher_testing:policy_validator:enabled_list", "");
        F4 = o40.b("gads:policy_validator_layoutparam:flags", 808);
        G4 = o40.a(2, "NATIVE_AD_DEBUGGER_ENABLED", bool12);
        H4 = o40.b("gads:policy_validator_overlay_width:dp", 350);
        I4 = o40.b("gads:policy_validator_overlay_height:dp", 140);
        J4 = o40.a(1, "gads:use_wide_viewport:enabled", bool11);
        K4 = o40.a(1, "gads:load_with_overview_mode:enabled", bool11);
        L4 = o40.a(1, "gads:wire_banner_listener_after_request:enabled", bool11);
        M4 = o40.a(1, "gads:wire_app_open_listener_after_request:enabled", bool11);
        N4 = o40.a(1, "gads:wire_interstitial_listener_after_request:enabled", bool11);
        O4 = o40.c("gads:server_transaction_source:list", "Network");
        P4 = o40.a(1, "gads:can_open_app_and_open_app_action:enabled", bool11);
        Q4 = o40.a(1, "gads:open_gmsg:set_uri_data_and_type:enabled", bool11);
        R4 = o40.b("gads:ad_error_api:min_version", 202006000);
        S4 = o40.a(1, "gads:forward_bow_error_string:enabled", bool12);
        T4 = o40.a(1, "gads:continue_on_process_response:enabled", bool11);
        U4 = o40.a(1, "gads:mediation_status_reporting:enabled", bool12);
        V4 = o40.b("gads:mediation_no_fill_error:min_version", 999999999);
        W4 = o40.b("gads:offline_database_version:version", 1);
        X4 = o40.a(1, "gads:offline_ads_notification:enabled", bool12);
        Y4 = o40.a(1, "gads:handle_click_recorded_event:enabled", bool11);
        Z4 = o40.a(1, "gads:default_network_type_fine_to_unknown:enabled", bool12);
        a5 = o40.a(1, "gads:handle_intent_async:enabled", bool11);
        b5 = o40.a(1, "gads:skip_deep_link_validation_native_ads:enabled", bool11);
        c5 = o40.a(1, "gads:try_deep_link_fallback_native_ads:enabled", bool11);
        d5 = o40.a(1, "gads:in_app_link_handling_for_android_11_enabled:enabled", bool11);
        e5 = o40.a(1, "gads:new_remote_logging_utils:enabled", bool11);
        f5 = o40.a(1, "gads:remote_logging:enabled", bool11);
        g5 = o40.b("gads:remote_log_send_rate_ms", 60000);
        h5 = o40.b("gads:remote_log_queue_max_entries", 500);
        i5 = o40.b("gads:app_event_queue_size", 20);
        Boolean bool13 = Boolean.FALSE;
        j5 = o40.a(1, "gads:hide_grey_title_bar:enabled", bool13);
        k5 = o40.a(1, "gads:interstitial_ad_parameter_handler:enabled", bool13);
    }

    public static void a(final Context context) {
        zzbr.zza(new gt2(context) { // from class: a50
            public final Context a;

            {
                this.a = context;
            }

            @Override // defpackage.gt2
            public final Object get() {
                Context context2 = this.a;
                u40 u40Var = os3.j.f;
                if (u40Var.c) {
                    return null;
                }
                synchronized (u40Var.a) {
                    if (u40Var.c) {
                        return null;
                    }
                    if (!u40Var.d) {
                        u40Var.d = true;
                    }
                    Context applicationContext = context2.getApplicationContext() == null ? context2 : context2.getApplicationContext();
                    u40Var.g = applicationContext;
                    try {
                        u40Var.f = i20.a(applicationContext).a(u40Var.g.getPackageName(), 128).metaData;
                    } catch (PackageManager.NameNotFoundException | NullPointerException unused) {
                    }
                    try {
                        Context contextA = ky.a(context2);
                        if (contextA == null) {
                            Context applicationContext2 = context2.getApplicationContext();
                            if (applicationContext2 != null) {
                                context2 = applicationContext2;
                            }
                            contextA = context2;
                        }
                        v40 v40Var = os3.j.e;
                        SharedPreferences sharedPreferences = contextA.getSharedPreferences("google_ads_flags", 0);
                        u40Var.e = sharedPreferences;
                        if (sharedPreferences != null) {
                            sharedPreferences.registerOnSharedPreferenceChangeListener(u40Var);
                        }
                        f70.a.set(new z40(u40Var));
                        u40Var.b();
                        u40Var.c = true;
                        return null;
                    } finally {
                        u40Var.d = false;
                        u40Var.b.open();
                    }
                }
            }
        });
    }

    public static List<String> b() {
        return os3.j.d.a();
    }

    public static List<String> c() {
        t40 t40Var = os3.j.d;
        List<String> listA = t40Var.a();
        Iterator<o40<String>> it = t40Var.c.iterator();
        while (it.hasNext()) {
            String str = (String) os3.j.f.a(it.next());
            if (!TextUtils.isEmpty(str)) {
                ((ArrayList) listA).add(str);
            }
        }
        ArrayList arrayList = new ArrayList();
        c50.r2(arrayList, y60.a);
        ((ArrayList) listA).addAll(arrayList);
        return listA;
    }
}
