package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import defpackage.bi;
import defpackage.dm0;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* loaded from: classes.dex */
public final class zzatq extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzatq> CREATOR = new dm0();
    public final List<String> A;
    public final String B;
    public final zzaei C;
    public final List<String> D;
    public final long E;
    public final String F;
    public final float G;
    public final int H;
    public final int I;
    public final boolean J;
    public final String K;
    public final boolean L;
    public final String M;
    public final boolean N;
    public final int O;
    public final Bundle P;
    public final String Q;
    public final zzzj R;
    public final boolean S;
    public final Bundle T;
    public final String U;
    public final String V;
    public final String W;
    public final boolean X;
    public final List<Integer> Y;
    public final String Z;
    public final List<String> a0;
    public final int b0;
    public final boolean c0;
    public final boolean d0;
    public final int e;
    public final boolean e0;
    public final Bundle f;
    public final ArrayList<String> f0;
    public final zzvq g;
    public final String g0;
    public final zzvt h;
    public final zzajy h0;
    public final String i;
    public final String i0;
    public final ApplicationInfo j;
    public final Bundle j0;
    public final PackageInfo k;
    public final String l;
    public final String m;
    public final String n;
    public final zzbar o;
    public final Bundle p;
    public final int q;
    public final List<String> r;
    public final Bundle s;
    public final boolean t;
    public final int u;
    public final int v;
    public final float w;
    public final String x;
    public final long y;
    public final String z;

    public zzatq(int i, Bundle bundle, zzvq zzvqVar, zzvt zzvtVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, zzbar zzbarVar, Bundle bundle2, int i2, List<String> list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List<String> list2, String str7, zzaei zzaeiVar, List<String> list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, zzzj zzzjVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List<Integer> list4, String str15, List<String> list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList<String> arrayList, String str16, zzajy zzajyVar, String str17, Bundle bundle6) {
        this.e = i;
        this.f = bundle;
        this.g = zzvqVar;
        this.h = zzvtVar;
        this.i = str;
        this.j = applicationInfo;
        this.k = packageInfo;
        this.l = str2;
        this.m = str3;
        this.n = str4;
        this.o = zzbarVar;
        this.p = bundle2;
        this.q = i2;
        this.r = list;
        this.D = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.s = bundle3;
        this.t = z;
        this.u = i3;
        this.v = i4;
        this.w = f;
        this.x = str5;
        this.y = j;
        this.z = str6;
        this.A = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.B = str7;
        this.C = zzaeiVar;
        this.E = j2;
        this.F = str8;
        this.G = f2;
        this.L = z2;
        this.H = i5;
        this.I = i6;
        this.J = z3;
        this.K = str9;
        this.M = str10;
        this.N = z4;
        this.O = i7;
        this.P = bundle4;
        this.Q = str11;
        this.R = zzzjVar;
        this.S = z5;
        this.T = bundle5;
        this.U = str12;
        this.V = str13;
        this.W = str14;
        this.X = z6;
        this.Y = list4;
        this.Z = str15;
        this.a0 = list5;
        this.b0 = i8;
        this.c0 = z7;
        this.d0 = z8;
        this.e0 = z9;
        this.f0 = arrayList;
        this.g0 = str16;
        this.h0 = zzajyVar;
        this.i0 = str17;
        this.j0 = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int iM0 = bi.m0(parcel, 20293);
        int i2 = this.e;
        bi.r0(parcel, 1, 4);
        parcel.writeInt(i2);
        bi.c0(parcel, 2, this.f, false);
        bi.h0(parcel, 3, this.g, i, false);
        bi.h0(parcel, 4, this.h, i, false);
        bi.i0(parcel, 5, this.i, false);
        bi.h0(parcel, 6, this.j, i, false);
        bi.h0(parcel, 7, this.k, i, false);
        bi.i0(parcel, 8, this.l, false);
        bi.i0(parcel, 9, this.m, false);
        bi.i0(parcel, 10, this.n, false);
        bi.h0(parcel, 11, this.o, i, false);
        bi.c0(parcel, 12, this.p, false);
        int i3 = this.q;
        bi.r0(parcel, 13, 4);
        parcel.writeInt(i3);
        bi.k0(parcel, 14, this.r, false);
        bi.c0(parcel, 15, this.s, false);
        boolean z = this.t;
        bi.r0(parcel, 16, 4);
        parcel.writeInt(z ? 1 : 0);
        int i4 = this.u;
        bi.r0(parcel, 18, 4);
        parcel.writeInt(i4);
        int i5 = this.v;
        bi.r0(parcel, 19, 4);
        parcel.writeInt(i5);
        float f = this.w;
        bi.r0(parcel, 20, 4);
        parcel.writeFloat(f);
        bi.i0(parcel, 21, this.x, false);
        long j = this.y;
        bi.r0(parcel, 25, 8);
        parcel.writeLong(j);
        bi.i0(parcel, 26, this.z, false);
        bi.k0(parcel, 27, this.A, false);
        bi.i0(parcel, 28, this.B, false);
        bi.h0(parcel, 29, this.C, i, false);
        bi.k0(parcel, 30, this.D, false);
        long j2 = this.E;
        bi.r0(parcel, 31, 8);
        parcel.writeLong(j2);
        bi.i0(parcel, 33, this.F, false);
        float f2 = this.G;
        bi.r0(parcel, 34, 4);
        parcel.writeFloat(f2);
        int i6 = this.H;
        bi.r0(parcel, 35, 4);
        parcel.writeInt(i6);
        int i7 = this.I;
        bi.r0(parcel, 36, 4);
        parcel.writeInt(i7);
        boolean z2 = this.J;
        bi.r0(parcel, 37, 4);
        parcel.writeInt(z2 ? 1 : 0);
        bi.i0(parcel, 39, this.K, false);
        boolean z3 = this.L;
        bi.r0(parcel, 40, 4);
        parcel.writeInt(z3 ? 1 : 0);
        bi.i0(parcel, 41, this.M, false);
        boolean z4 = this.N;
        bi.r0(parcel, 42, 4);
        parcel.writeInt(z4 ? 1 : 0);
        int i8 = this.O;
        bi.r0(parcel, 43, 4);
        parcel.writeInt(i8);
        bi.c0(parcel, 44, this.P, false);
        bi.i0(parcel, 45, this.Q, false);
        bi.h0(parcel, 46, this.R, i, false);
        boolean z5 = this.S;
        bi.r0(parcel, 47, 4);
        parcel.writeInt(z5 ? 1 : 0);
        bi.c0(parcel, 48, this.T, false);
        bi.i0(parcel, 49, this.U, false);
        bi.i0(parcel, 50, this.V, false);
        bi.i0(parcel, 51, this.W, false);
        boolean z6 = this.X;
        bi.r0(parcel, 52, 4);
        parcel.writeInt(z6 ? 1 : 0);
        List<Integer> list = this.Y;
        if (list != null) {
            int iM02 = bi.m0(parcel, 53);
            int size = list.size();
            parcel.writeInt(size);
            for (int i9 = 0; i9 < size; i9++) {
                parcel.writeInt(list.get(i9).intValue());
            }
            bi.t0(parcel, iM02);
        }
        bi.i0(parcel, 54, this.Z, false);
        bi.k0(parcel, 55, this.a0, false);
        int i10 = this.b0;
        bi.r0(parcel, 56, 4);
        parcel.writeInt(i10);
        boolean z7 = this.c0;
        bi.r0(parcel, 57, 4);
        parcel.writeInt(z7 ? 1 : 0);
        boolean z8 = this.d0;
        bi.r0(parcel, 58, 4);
        parcel.writeInt(z8 ? 1 : 0);
        boolean z9 = this.e0;
        bi.r0(parcel, 59, 4);
        parcel.writeInt(z9 ? 1 : 0);
        bi.k0(parcel, 60, this.f0, false);
        bi.i0(parcel, 61, this.g0, false);
        bi.h0(parcel, 63, this.h0, i, false);
        bi.i0(parcel, 64, this.i0, false);
        bi.c0(parcel, 65, this.j0, false);
        bi.t0(parcel, iM0);
    }
}
